[2024-01-18 12:08:06,636][0][INFO][color_logger.py:203] Logfile: /data1/xiayuyang/online_mcmt/logs/0_2024-01-18-12-08-06-636598.log
[2024-01-18 12:08:06,711][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '1',
  'fps_camera3': '1',
  'fps_camera4': '1',
  'fps_camera5': '1',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-18 12:08:06,712][0][INFO][generic_smbo.py:295] Iter 1, objectives: [inf, inf].
[2024-01-18 12:08:06,712][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '4',
  'fps_camera3': '4',
  'fps_camera4': '10',
  'fps_camera5': '4',
  'lazy_threshold': 0.78,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '640',
  'resolution_camera5': '320',
})

[2024-01-18 12:08:06,712][0][INFO][generic_smbo.py:295] Iter 2, objectives: [inf, inf].
[2024-01-18 12:08:06,713][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '10',
  'fps_camera3': '1',
  'fps_camera4': '2',
  'fps_camera5': '2',
  'lazy_threshold': 0.86,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '640',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-18 12:08:06,713][0][INFO][generic_smbo.py:295] Iter 3, objectives: [inf, inf].
[2024-01-18 12:08:06,713][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '1',
  'fps_camera3': '10',
  'fps_camera4': '10',
  'fps_camera5': '4',
  'lazy_threshold': 0.64,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-18 12:08:06,714][0][INFO][generic_smbo.py:295] Iter 4, objectives: [inf, inf].
[2024-01-18 12:08:06,714][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '1',
  'fps_camera3': '1',
  'fps_camera4': '1',
  'fps_camera5': '10',
  'lazy_threshold': 0.6,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '640',
  'resolution_camera3': '640',
  'resolution_camera4': '640',
  'resolution_camera5': '640',
})

[2024-01-18 12:08:06,714][0][INFO][generic_smbo.py:295] Iter 5, objectives: [inf, inf].
[2024-01-18 12:08:06,715][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '1',
  'fps_camera3': '10',
  'fps_camera4': '4',
  'fps_camera5': '1',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-18 12:08:06,715][0][INFO][generic_smbo.py:295] Iter 6, objectives: [inf, inf].
[2024-01-18 12:08:06,715][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '10',
  'fps_camera3': '10',
  'fps_camera4': '10',
  'fps_camera5': '2',
  'lazy_threshold': 0.8999999999999999,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-18 12:08:06,716][0][INFO][generic_smbo.py:295] Iter 7, objectives: [inf, inf].
[2024-01-18 12:08:06,716][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '1',
  'fps_camera3': '10',
  'fps_camera4': '1',
  'fps_camera5': '10',
  'lazy_threshold': 0.6,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '640',
  'resolution_camera4': '1280',
  'resolution_camera5': '640',
})

[2024-01-18 12:08:06,716][0][INFO][generic_smbo.py:295] Iter 8, objectives: [inf, inf].
[2024-01-18 12:08:06,717][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '1',
  'fps_camera3': '1',
  'fps_camera4': '4',
  'fps_camera5': '1',
  'lazy_threshold': 0.6599999999999999,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-18 12:08:06,717][0][INFO][generic_smbo.py:295] Iter 9, objectives: [inf, inf].
[2024-01-18 12:08:06,718][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:06,719][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '1',
  'fps_camera3': '10',
  'fps_camera4': '1',
  'fps_camera5': '2',
  'lazy_threshold': 0.84,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '1280',
  'resolution_camera5': '640',
})

[2024-01-18 12:08:06,719][0][INFO][generic_smbo.py:295] Iter 10, objectives: [inf, inf].
[2024-01-18 12:08:06,720][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:06,721][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '1',
  'fps_camera3': '10',
  'fps_camera4': '4',
  'fps_camera5': '10',
  'lazy_threshold': 0.8,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '640',
  'resolution_camera5': '640',
})

[2024-01-18 12:08:06,721][0][INFO][generic_smbo.py:295] Iter 11, objectives: [inf, inf].
[2024-01-18 12:08:06,722][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:06,723][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '10',
  'fps_camera3': '1',
  'fps_camera4': '4',
  'fps_camera5': '2',
  'lazy_threshold': 0.78,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '640',
  'resolution_camera5': '640',
})

[2024-01-18 12:08:06,723][0][INFO][generic_smbo.py:295] Iter 12, objectives: [inf, inf].
[2024-01-18 12:08:06,723][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:06,725][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '4',
  'fps_camera3': '4',
  'fps_camera4': '2',
  'fps_camera5': '2',
  'lazy_threshold': 0.76,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '640',
  'resolution_camera5': '320',
})

[2024-01-18 12:08:06,726][0][INFO][generic_smbo.py:295] Iter 13, objectives: [inf, inf].
[2024-01-18 12:08:06,726][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:06,727][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '1',
  'fps_camera3': '10',
  'fps_camera4': '2',
  'fps_camera5': '4',
  'lazy_threshold': 0.8999999999999999,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '640',
})

[2024-01-18 12:08:06,728][0][INFO][generic_smbo.py:295] Iter 14, objectives: [inf, inf].
[2024-01-18 12:08:06,728][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:06,729][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '10',
  'fps_camera3': '10',
  'fps_camera4': '4',
  'fps_camera5': '1',
  'lazy_threshold': 0.6799999999999999,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-18 12:08:06,730][0][INFO][generic_smbo.py:295] Iter 15, objectives: [inf, inf].
[2024-01-18 12:08:06,730][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:06,731][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '2',
  'fps_camera3': '4',
  'fps_camera4': '2',
  'fps_camera5': '2',
  'lazy_threshold': 0.72,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '640',
  'resolution_camera3': '1280',
  'resolution_camera4': '640',
  'resolution_camera5': '640',
})

[2024-01-18 12:08:06,731][0][INFO][generic_smbo.py:295] Iter 16, objectives: [inf, inf].
[2024-01-18 12:08:06,732][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:06,733][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '4',
  'fps_camera3': '10',
  'fps_camera4': '4',
  'fps_camera5': '1',
  'lazy_threshold': 0.62,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-18 12:08:06,733][0][INFO][generic_smbo.py:295] Iter 17, objectives: [inf, inf].
[2024-01-18 12:08:06,734][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:06,735][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '4',
  'fps_camera3': '2',
  'fps_camera4': '1',
  'fps_camera5': '1',
  'lazy_threshold': 0.84,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '640',
  'resolution_camera5': '640',
})

[2024-01-18 12:08:06,735][0][INFO][generic_smbo.py:295] Iter 18, objectives: [inf, inf].
[2024-01-18 12:08:06,736][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:06,737][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '2',
  'fps_camera3': '4',
  'fps_camera4': '10',
  'fps_camera5': '4',
  'lazy_threshold': 0.76,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '640',
  'resolution_camera5': '640',
})

[2024-01-18 12:08:06,737][0][INFO][generic_smbo.py:295] Iter 19, objectives: [inf, inf].
[2024-01-18 12:08:06,738][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:06,739][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '10',
  'fps_camera3': '4',
  'fps_camera4': '1',
  'fps_camera5': '10',
  'lazy_threshold': 0.62,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-18 12:08:06,739][0][INFO][generic_smbo.py:295] Iter 20, objectives: [inf, inf].
[2024-01-18 12:08:06,740][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:06,741][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '10',
  'fps_camera3': '10',
  'fps_camera4': '4',
  'fps_camera5': '2',
  'lazy_threshold': 0.78,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '640',
  'resolution_camera3': '640',
  'resolution_camera4': '640',
  'resolution_camera5': '320',
})

[2024-01-18 12:08:06,741][0][INFO][generic_smbo.py:295] Iter 21, objectives: [inf, inf].
[2024-01-18 12:08:06,742][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:06,743][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '2',
  'fps_camera3': '4',
  'fps_camera4': '2',
  'fps_camera5': '1',
  'lazy_threshold': 0.86,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '640',
  'resolution_camera3': '1280',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-18 12:08:06,743][0][INFO][generic_smbo.py:295] Iter 22, objectives: [inf, inf].
[2024-01-18 12:08:06,743][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:06,744][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '2',
  'fps_camera3': '1',
  'fps_camera4': '4',
  'fps_camera5': '2',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-18 12:08:09,738][0][INFO][generic_smbo.py:295] Iter 23, objectives: [inf, inf].
[2024-01-18 12:08:09,739][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:09,740][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '4',
  'fps_camera3': '2',
  'fps_camera4': '4',
  'fps_camera5': '4',
  'lazy_threshold': 0.88,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-18 12:08:09,741][0][INFO][generic_smbo.py:295] Iter 24, objectives: [inf, inf].
[2024-01-18 12:08:09,741][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:09,742][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '1',
  'fps_camera3': '4',
  'fps_camera4': '4',
  'fps_camera5': '1',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '640',
  'resolution_camera5': '1280',
})

[2024-01-18 12:08:09,743][0][INFO][generic_smbo.py:295] Iter 25, objectives: [inf, inf].
[2024-01-18 12:08:09,743][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:09,744][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '2',
  'fps_camera3': '4',
  'fps_camera4': '2',
  'fps_camera5': '2',
  'lazy_threshold': 0.78,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '640',
})

[2024-01-18 12:08:09,745][0][INFO][generic_smbo.py:295] Iter 26, objectives: [inf, inf].
[2024-01-18 12:08:09,745][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:09,746][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '10',
  'fps_camera3': '10',
  'fps_camera4': '10',
  'fps_camera5': '2',
  'lazy_threshold': 0.88,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '640',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-18 12:08:09,746][0][INFO][generic_smbo.py:295] Iter 27, objectives: [inf, inf].
[2024-01-18 12:08:09,747][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:09,748][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '4',
  'fps_camera3': '1',
  'fps_camera4': '4',
  'fps_camera5': '2',
  'lazy_threshold': 0.82,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '320',
})

[2024-01-18 12:08:09,752][0][INFO][generic_smbo.py:295] Iter 28, objectives: [inf, inf].
[2024-01-18 12:08:09,752][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-01-18 12:08:09,753][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '4',
  'fps_camera3': '4',
  'fps_camera4': '4',
  'fps_camera5': '1',
  'lazy_threshold': 0.6,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-18 12:08:09,753][0][INFO][generic_smbo.py:295] Iter 29, objectives: [inf, inf].
[2024-01-18 12:08:09,754][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:09,755][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '1',
  'fps_camera3': '1',
  'fps_camera4': '1',
  'fps_camera5': '1',
  'lazy_threshold': 0.62,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '320',
  'resolution_camera5': '640',
})

[2024-01-18 12:08:09,755][0][INFO][generic_smbo.py:295] Iter 30, objectives: [inf, inf].
[2024-01-18 12:08:09,756][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:09,757][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '2',
  'fps_camera3': '1',
  'fps_camera4': '2',
  'fps_camera5': '2',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '640',
  'resolution_camera3': '320',
  'resolution_camera4': '640',
  'resolution_camera5': '320',
})

[2024-01-18 12:08:09,758][0][INFO][generic_smbo.py:295] Iter 31, objectives: [inf, inf].
[2024-01-18 12:08:09,758][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:09,759][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '10',
  'fps_camera3': '4',
  'fps_camera4': '2',
  'fps_camera5': '4',
  'lazy_threshold': 0.74,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '640',
  'resolution_camera5': '1280',
})

[2024-01-18 12:08:09,760][0][INFO][generic_smbo.py:295] Iter 32, objectives: [inf, inf].
[2024-01-18 12:08:09,760][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:09,762][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '4',
  'fps_camera3': '2',
  'fps_camera4': '1',
  'fps_camera5': '10',
  'lazy_threshold': 0.6799999999999999,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '640',
  'resolution_camera5': '1280',
})

[2024-01-18 12:08:09,762][0][INFO][generic_smbo.py:295] Iter 33, objectives: [inf, inf].
[2024-01-18 12:08:09,762][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-01-18 12:08:09,763][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '2',
  'fps_camera3': '1',
  'fps_camera4': '2',
  'fps_camera5': '4',
  'lazy_threshold': 0.72,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-18 12:08:09,764][0][INFO][generic_smbo.py:295] Iter 34, objectives: [inf, inf].
[2024-01-18 12:08:09,764][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:09,766][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '2',
  'fps_camera3': '2',
  'fps_camera4': '1',
  'fps_camera5': '2',
  'lazy_threshold': 0.64,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-18 12:08:09,766][0][INFO][generic_smbo.py:295] Iter 35, objectives: [inf, inf].
[2024-01-18 12:08:09,767][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:09,768][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '4',
  'fps_camera3': '4',
  'fps_camera4': '4',
  'fps_camera5': '4',
  'lazy_threshold': 0.6,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '640',
  'resolution_camera5': '1280',
})

[2024-01-18 12:08:09,768][0][INFO][generic_smbo.py:295] Iter 36, objectives: [inf, inf].
[2024-01-18 12:08:09,769][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:09,770][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '4',
  'fps_camera3': '1',
  'fps_camera4': '4',
  'fps_camera5': '2',
  'lazy_threshold': 0.82,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '640',
  'resolution_camera5': '1280',
})

[2024-01-18 12:08:09,770][0][INFO][generic_smbo.py:295] Iter 37, objectives: [inf, inf].
[2024-01-18 12:08:09,771][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:09,772][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '2',
  'fps_camera3': '4',
  'fps_camera4': '4',
  'fps_camera5': '10',
  'lazy_threshold': 0.72,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '320',
})

[2024-01-18 12:08:09,773][0][INFO][generic_smbo.py:295] Iter 38, objectives: [inf, inf].
[2024-01-18 12:08:09,773][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:09,775][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '10',
  'fps_camera3': '10',
  'fps_camera4': '2',
  'fps_camera5': '4',
  'lazy_threshold': 0.8,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '640',
  'resolution_camera3': '320',
  'resolution_camera4': '640',
  'resolution_camera5': '1280',
})

[2024-01-18 12:08:09,775][0][INFO][generic_smbo.py:295] Iter 39, objectives: [inf, inf].
[2024-01-18 12:08:09,776][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:09,777][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '4',
  'fps_camera3': '10',
  'fps_camera4': '1',
  'fps_camera5': '4',
  'lazy_threshold': 0.8,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '640',
  'resolution_camera3': '320',
  'resolution_camera4': '640',
  'resolution_camera5': '640',
})

[2024-01-18 12:08:09,777][0][INFO][generic_smbo.py:295] Iter 40, objectives: [inf, inf].
[2024-01-18 12:08:09,778][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:09,779][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '4',
  'fps_camera3': '10',
  'fps_camera4': '4',
  'fps_camera5': '1',
  'lazy_threshold': 0.82,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '640',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-18 12:08:09,779][0][INFO][generic_smbo.py:295] Iter 41, objectives: [inf, inf].
[2024-01-18 12:08:09,780][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:09,781][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '4',
  'fps_camera3': '2',
  'fps_camera4': '4',
  'fps_camera5': '2',
  'lazy_threshold': 0.82,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '640',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '320',
})

[2024-01-18 12:08:09,782][0][INFO][generic_smbo.py:295] Iter 42, objectives: [inf, inf].
[2024-01-18 12:08:09,782][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-01-18 12:08:09,783][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '10',
  'fps_camera3': '1',
  'fps_camera4': '1',
  'fps_camera5': '2',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '640',
})

[2024-01-18 12:08:09,784][0][INFO][generic_smbo.py:295] Iter 43, objectives: [inf, inf].
[2024-01-18 12:08:09,784][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:09,786][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '10',
  'fps_camera3': '10',
  'fps_camera4': '2',
  'fps_camera5': '1',
  'lazy_threshold': 0.82,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '640',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-18 12:08:09,786][0][INFO][generic_smbo.py:295] Iter 44, objectives: [inf, inf].
[2024-01-18 12:08:09,787][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:09,788][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '10',
  'fps_camera3': '2',
  'fps_camera4': '4',
  'fps_camera5': '1',
  'lazy_threshold': 0.78,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-18 12:08:09,789][0][INFO][generic_smbo.py:295] Iter 45, objectives: [inf, inf].
[2024-01-18 12:08:09,789][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:09,791][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '10',
  'fps_camera3': '10',
  'fps_camera4': '2',
  'fps_camera5': '4',
  'lazy_threshold': 0.74,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '640',
  'resolution_camera3': '1280',
  'resolution_camera4': '640',
  'resolution_camera5': '640',
})

[2024-01-18 12:08:09,791][0][INFO][generic_smbo.py:295] Iter 46, objectives: [inf, inf].
[2024-01-18 12:08:09,792][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:09,793][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '10',
  'fps_camera3': '1',
  'fps_camera4': '10',
  'fps_camera5': '2',
  'lazy_threshold': 0.76,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '640',
})

[2024-01-18 12:08:09,793][0][INFO][generic_smbo.py:295] Iter 47, objectives: [inf, inf].
[2024-01-18 12:08:09,794][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:09,795][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '1',
  'fps_camera3': '2',
  'fps_camera4': '4',
  'fps_camera5': '10',
  'lazy_threshold': 0.64,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-18 12:08:09,796][0][INFO][generic_smbo.py:295] Iter 48, objectives: [inf, inf].
[2024-01-18 12:08:09,796][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:09,798][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '1',
  'fps_camera3': '2',
  'fps_camera4': '4',
  'fps_camera5': '2',
  'lazy_threshold': 0.6,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '640',
  'resolution_camera5': '320',
})

[2024-01-18 12:08:09,798][0][INFO][generic_smbo.py:295] Iter 49, objectives: [inf, inf].
[2024-01-18 12:08:09,799][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:08:09,800][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '2',
  'fps_camera3': '4',
  'fps_camera4': '1',
  'fps_camera5': '10',
  'lazy_threshold': 0.76,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '640',
})

[2024-01-18 12:08:09,801][0][INFO][generic_smbo.py:295] Iter 50, objectives: [inf, inf].
[2024-01-18 12:08:09,807][0][WARNING][history.py:651] No feasible observations! Return empty pareto.
