[2024-01-18 12:09:57,576][0][INFO][color_logger.py:203] Logfile: /data1/xiayuyang/online_mcmt/logs/0_2024-01-18-12-09-57-576233.log
[2024-01-18 12:09:57,649][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '1',
  'fps_camera3': '1',
  'fps_camera4': '1',
  'fps_camera5': '1',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-18 12:09:57,649][0][INFO][generic_smbo.py:295] Iter 1, objectives: [inf, inf].
[2024-01-18 12:09:57,650][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '10',
  'fps_camera3': '10',
  'fps_camera4': '10',
  'fps_camera5': '10',
  'lazy_threshold': 0.8,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-18 12:09:57,650][0][INFO][generic_smbo.py:295] Iter 2, objectives: [inf, inf].
[2024-01-18 12:09:57,651][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '1',
  'fps_camera3': '1',
  'fps_camera4': '10',
  'fps_camera5': '4',
  'lazy_threshold': 0.6799999999999999,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '640',
})

[2024-01-18 12:09:57,651][0][INFO][generic_smbo.py:295] Iter 3, objectives: [inf, inf].
[2024-01-18 12:09:57,651][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '2',
  'fps_camera3': '10',
  'fps_camera4': '1',
  'fps_camera5': '2',
  'lazy_threshold': 0.6,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '320',
  'resolution_camera5': '640',
})

[2024-01-18 12:09:57,652][0][INFO][generic_smbo.py:295] Iter 4, objectives: [inf, inf].
[2024-01-18 12:09:57,652][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '10',
  'fps_camera3': '1',
  'fps_camera4': '1',
  'fps_camera5': '1',
  'lazy_threshold': 0.84,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-18 12:09:57,652][0][INFO][generic_smbo.py:295] Iter 5, objectives: [inf, inf].
[2024-01-18 12:09:57,653][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '10',
  'fps_camera3': '2',
  'fps_camera4': '10',
  'fps_camera5': '4',
  'lazy_threshold': 0.6599999999999999,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '640',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-18 12:09:57,653][0][INFO][generic_smbo.py:295] Iter 6, objectives: [inf, inf].
[2024-01-18 12:09:57,653][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '1',
  'fps_camera3': '2',
  'fps_camera4': '2',
  'fps_camera5': '10',
  'lazy_threshold': 0.6599999999999999,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '640',
})

[2024-01-18 12:09:57,653][0][INFO][generic_smbo.py:295] Iter 7, objectives: [inf, inf].
[2024-01-18 12:09:57,654][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '2',
  'fps_camera3': '10',
  'fps_camera4': '10',
  'fps_camera5': '10',
  'lazy_threshold': 0.6599999999999999,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-18 12:09:57,654][0][INFO][generic_smbo.py:295] Iter 8, objectives: [inf, inf].
[2024-01-18 12:09:57,655][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '10',
  'fps_camera3': '1',
  'fps_camera4': '4',
  'fps_camera5': '1',
  'lazy_threshold': 0.6799999999999999,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '640',
  'resolution_camera3': '640',
  'resolution_camera4': '1280',
  'resolution_camera5': '320',
})

[2024-01-18 12:09:57,655][0][INFO][generic_smbo.py:295] Iter 9, objectives: [inf, inf].
[2024-01-18 12:09:57,656][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:57,657][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '10',
  'fps_camera3': '2',
  'fps_camera4': '1',
  'fps_camera5': '1',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-18 12:09:57,657][0][INFO][generic_smbo.py:295] Iter 10, objectives: [inf, inf].
[2024-01-18 12:09:57,658][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:57,659][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '10',
  'fps_camera3': '10',
  'fps_camera4': '4',
  'fps_camera5': '2',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '640',
  'resolution_camera5': '320',
})

[2024-01-18 12:09:57,662][0][INFO][generic_smbo.py:295] Iter 11, objectives: [inf, inf].
[2024-01-18 12:09:57,663][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:57,664][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '2',
  'fps_camera3': '10',
  'fps_camera4': '2',
  'fps_camera5': '4',
  'lazy_threshold': 0.72,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-18 12:09:57,664][0][INFO][generic_smbo.py:295] Iter 12, objectives: [inf, inf].
[2024-01-18 12:09:57,664][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-01-18 12:09:57,665][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '1',
  'fps_camera3': '1',
  'fps_camera4': '1',
  'fps_camera5': '1',
  'lazy_threshold': 0.74,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '640',
})

[2024-01-18 12:09:57,666][0][INFO][generic_smbo.py:295] Iter 13, objectives: [inf, inf].
[2024-01-18 12:09:57,666][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:57,668][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '4',
  'fps_camera3': '10',
  'fps_camera4': '4',
  'fps_camera5': '10',
  'lazy_threshold': 0.6799999999999999,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '640',
  'resolution_camera4': '640',
  'resolution_camera5': '640',
})

[2024-01-18 12:09:57,668][0][INFO][generic_smbo.py:295] Iter 14, objectives: [inf, inf].
[2024-01-18 12:09:57,668][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:57,669][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '4',
  'fps_camera3': '4',
  'fps_camera4': '4',
  'fps_camera5': '10',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '640',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-18 12:09:57,670][0][INFO][generic_smbo.py:295] Iter 15, objectives: [inf, inf].
[2024-01-18 12:09:57,670][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-01-18 12:09:57,671][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '2',
  'fps_camera3': '10',
  'fps_camera4': '4',
  'fps_camera5': '2',
  'lazy_threshold': 0.78,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '320',
})

[2024-01-18 12:09:57,672][0][INFO][generic_smbo.py:295] Iter 16, objectives: [inf, inf].
[2024-01-18 12:09:57,672][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:57,673][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '10',
  'fps_camera3': '10',
  'fps_camera4': '1',
  'fps_camera5': '4',
  'lazy_threshold': 0.78,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '640',
  'resolution_camera3': '640',
  'resolution_camera4': '640',
  'resolution_camera5': '1280',
})

[2024-01-18 12:09:57,674][0][INFO][generic_smbo.py:295] Iter 17, objectives: [inf, inf].
[2024-01-18 12:09:57,674][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-01-18 12:09:57,675][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '2',
  'fps_camera3': '1',
  'fps_camera4': '1',
  'fps_camera5': '1',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '1280',
  'resolution_camera5': '320',
})

[2024-01-18 12:09:57,675][0][INFO][generic_smbo.py:295] Iter 18, objectives: [inf, inf].
[2024-01-18 12:09:57,676][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:57,677][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '2',
  'fps_camera3': '1',
  'fps_camera4': '2',
  'fps_camera5': '2',
  'lazy_threshold': 0.88,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '640',
  'resolution_camera3': '320',
  'resolution_camera4': '640',
  'resolution_camera5': '640',
})

[2024-01-18 12:09:57,677][0][INFO][generic_smbo.py:295] Iter 19, objectives: [inf, inf].
[2024-01-18 12:09:57,678][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:57,679][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '4',
  'fps_camera3': '1',
  'fps_camera4': '10',
  'fps_camera5': '1',
  'lazy_threshold': 0.76,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '640',
})

[2024-01-18 12:09:57,680][0][INFO][generic_smbo.py:295] Iter 20, objectives: [inf, inf].
[2024-01-18 12:09:57,680][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:57,681][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '2',
  'fps_camera3': '1',
  'fps_camera4': '4',
  'fps_camera5': '2',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-18 12:09:57,681][0][INFO][generic_smbo.py:295] Iter 21, objectives: [inf, inf].
[2024-01-18 12:09:57,682][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:57,683][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '4',
  'fps_camera3': '2',
  'fps_camera4': '1',
  'fps_camera5': '10',
  'lazy_threshold': 0.72,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '640',
  'resolution_camera5': '640',
})

[2024-01-18 12:09:59,858][0][INFO][generic_smbo.py:295] Iter 22, objectives: [inf, inf].
[2024-01-18 12:09:59,859][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:59,860][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '10',
  'fps_camera3': '4',
  'fps_camera4': '10',
  'fps_camera5': '4',
  'lazy_threshold': 0.74,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '640',
  'resolution_camera5': '640',
})

[2024-01-18 12:09:59,860][0][INFO][generic_smbo.py:295] Iter 23, objectives: [inf, inf].
[2024-01-18 12:09:59,861][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:59,862][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '2',
  'fps_camera3': '2',
  'fps_camera4': '2',
  'fps_camera5': '1',
  'lazy_threshold': 0.64,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '640',
  'resolution_camera3': '320',
  'resolution_camera4': '640',
  'resolution_camera5': '640',
})

[2024-01-18 12:09:59,862][0][INFO][generic_smbo.py:295] Iter 24, objectives: [inf, inf].
[2024-01-18 12:09:59,863][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:59,864][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '10',
  'fps_camera3': '1',
  'fps_camera4': '4',
  'fps_camera5': '4',
  'lazy_threshold': 0.6799999999999999,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '640',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-18 12:09:59,864][0][INFO][generic_smbo.py:295] Iter 25, objectives: [inf, inf].
[2024-01-18 12:09:59,865][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:59,866][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '2',
  'fps_camera3': '1',
  'fps_camera4': '2',
  'fps_camera5': '2',
  'lazy_threshold': 0.86,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '640',
  'resolution_camera3': '1280',
  'resolution_camera4': '640',
  'resolution_camera5': '320',
})

[2024-01-18 12:09:59,866][0][INFO][generic_smbo.py:295] Iter 26, objectives: [inf, inf].
[2024-01-18 12:09:59,867][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:59,868][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '4',
  'fps_camera3': '10',
  'fps_camera4': '10',
  'fps_camera5': '1',
  'lazy_threshold': 0.88,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '1280',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-18 12:09:59,871][0][INFO][generic_smbo.py:295] Iter 27, objectives: [inf, inf].
[2024-01-18 12:09:59,871][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:59,872][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '1',
  'fps_camera3': '10',
  'fps_camera4': '1',
  'fps_camera5': '10',
  'lazy_threshold': 0.72,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '640',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '640',
})

[2024-01-18 12:09:59,873][0][INFO][generic_smbo.py:295] Iter 28, objectives: [inf, inf].
[2024-01-18 12:09:59,873][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:59,874][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '10',
  'fps_camera3': '4',
  'fps_camera4': '10',
  'fps_camera5': '10',
  'lazy_threshold': 0.62,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-18 12:09:59,875][0][INFO][generic_smbo.py:295] Iter 29, objectives: [inf, inf].
[2024-01-18 12:09:59,875][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:59,876][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '4',
  'fps_camera3': '1',
  'fps_camera4': '4',
  'fps_camera5': '1',
  'lazy_threshold': 0.72,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '640',
  'resolution_camera3': '640',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-18 12:09:59,877][0][INFO][generic_smbo.py:295] Iter 30, objectives: [inf, inf].
[2024-01-18 12:09:59,877][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:59,878][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '4',
  'fps_camera3': '2',
  'fps_camera4': '2',
  'fps_camera5': '1',
  'lazy_threshold': 0.74,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-18 12:09:59,878][0][INFO][generic_smbo.py:295] Iter 31, objectives: [inf, inf].
[2024-01-18 12:09:59,879][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:59,880][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '2',
  'fps_camera3': '10',
  'fps_camera4': '1',
  'fps_camera5': '10',
  'lazy_threshold': 0.88,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '640',
})

[2024-01-18 12:09:59,881][0][INFO][generic_smbo.py:295] Iter 32, objectives: [inf, inf].
[2024-01-18 12:09:59,881][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:59,882][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '1',
  'fps_camera3': '2',
  'fps_camera4': '4',
  'fps_camera5': '2',
  'lazy_threshold': 0.6,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '320',
})

[2024-01-18 12:09:59,883][0][INFO][generic_smbo.py:295] Iter 33, objectives: [inf, inf].
[2024-01-18 12:09:59,883][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:59,885][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '10',
  'fps_camera3': '1',
  'fps_camera4': '1',
  'fps_camera5': '1',
  'lazy_threshold': 0.86,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '640',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-18 12:09:59,885][0][INFO][generic_smbo.py:295] Iter 34, objectives: [inf, inf].
[2024-01-18 12:09:59,885][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:59,887][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '4',
  'fps_camera3': '1',
  'fps_camera4': '4',
  'fps_camera5': '2',
  'lazy_threshold': 0.88,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-18 12:09:59,887][0][INFO][generic_smbo.py:295] Iter 35, objectives: [inf, inf].
[2024-01-18 12:09:59,888][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:59,889][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '10',
  'fps_camera3': '10',
  'fps_camera4': '4',
  'fps_camera5': '10',
  'lazy_threshold': 0.78,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '640',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '640',
})

[2024-01-18 12:09:59,889][0][INFO][generic_smbo.py:295] Iter 36, objectives: [inf, inf].
[2024-01-18 12:09:59,890][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:59,891][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '4',
  'fps_camera3': '1',
  'fps_camera4': '4',
  'fps_camera5': '4',
  'lazy_threshold': 0.84,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '640',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-18 12:09:59,897][0][INFO][generic_smbo.py:295] Iter 37, objectives: [inf, inf].
[2024-01-18 12:09:59,898][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:59,899][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '2',
  'fps_camera3': '2',
  'fps_camera4': '1',
  'fps_camera5': '4',
  'lazy_threshold': 0.76,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '640',
  'resolution_camera3': '640',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-18 12:09:59,900][0][INFO][generic_smbo.py:295] Iter 38, objectives: [inf, inf].
[2024-01-18 12:09:59,900][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:59,901][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '1',
  'fps_camera3': '1',
  'fps_camera4': '10',
  'fps_camera5': '4',
  'lazy_threshold': 0.6599999999999999,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-18 12:09:59,902][0][INFO][generic_smbo.py:295] Iter 39, objectives: [inf, inf].
[2024-01-18 12:09:59,902][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:59,903][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '10',
  'fps_camera3': '1',
  'fps_camera4': '2',
  'fps_camera5': '4',
  'lazy_threshold': 0.8999999999999999,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '640',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '320',
})

[2024-01-18 12:09:59,904][0][INFO][generic_smbo.py:295] Iter 40, objectives: [inf, inf].
[2024-01-18 12:09:59,904][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:59,906][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '4',
  'fps_camera3': '1',
  'fps_camera4': '1',
  'fps_camera5': '10',
  'lazy_threshold': 0.74,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '640',
  'resolution_camera3': '320',
  'resolution_camera4': '640',
  'resolution_camera5': '320',
})

[2024-01-18 12:09:59,906][0][INFO][generic_smbo.py:295] Iter 41, objectives: [inf, inf].
[2024-01-18 12:09:59,906][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:59,908][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '4',
  'fps_camera3': '1',
  'fps_camera4': '1',
  'fps_camera5': '4',
  'lazy_threshold': 0.82,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '640',
  'resolution_camera3': '1280',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-18 12:09:59,908][0][INFO][generic_smbo.py:295] Iter 42, objectives: [inf, inf].
[2024-01-18 12:09:59,908][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-01-18 12:09:59,912][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '2',
  'fps_camera3': '4',
  'fps_camera4': '4',
  'fps_camera5': '2',
  'lazy_threshold': 0.72,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '640',
  'resolution_camera5': '1280',
})

[2024-01-18 12:09:59,912][0][INFO][generic_smbo.py:295] Iter 43, objectives: [inf, inf].
[2024-01-18 12:09:59,913][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:59,914][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '4',
  'fps_camera3': '10',
  'fps_camera4': '1',
  'fps_camera5': '1',
  'lazy_threshold': 0.86,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '640',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '320',
})

[2024-01-18 12:09:59,914][0][INFO][generic_smbo.py:295] Iter 44, objectives: [inf, inf].
[2024-01-18 12:09:59,915][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:59,916][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '2',
  'fps_camera3': '10',
  'fps_camera4': '1',
  'fps_camera5': '10',
  'lazy_threshold': 0.86,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '640',
  'resolution_camera3': '640',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-18 12:09:59,917][0][INFO][generic_smbo.py:295] Iter 45, objectives: [inf, inf].
[2024-01-18 12:09:59,917][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:59,918][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '4',
  'fps_camera3': '1',
  'fps_camera4': '1',
  'fps_camera5': '10',
  'lazy_threshold': 0.84,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '640',
})

[2024-01-18 12:09:59,919][0][INFO][generic_smbo.py:295] Iter 46, objectives: [inf, inf].
[2024-01-18 12:09:59,919][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:59,921][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '4',
  'fps_camera3': '4',
  'fps_camera4': '2',
  'fps_camera5': '1',
  'lazy_threshold': 0.82,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '320',
  'resolution_camera5': '640',
})

[2024-01-18 12:09:59,921][0][INFO][generic_smbo.py:295] Iter 47, objectives: [inf, inf].
[2024-01-18 12:09:59,922][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:59,923][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '1',
  'fps_camera3': '2',
  'fps_camera4': '4',
  'fps_camera5': '4',
  'lazy_threshold': 0.88,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-18 12:09:59,923][0][INFO][generic_smbo.py:295] Iter 48, objectives: [inf, inf].
[2024-01-18 12:09:59,924][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-01-18 12:09:59,925][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '2',
  'fps_camera3': '2',
  'fps_camera4': '10',
  'fps_camera5': '2',
  'lazy_threshold': 0.76,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-18 12:09:59,925][0][INFO][generic_smbo.py:295] Iter 49, objectives: [inf, inf].
[2024-01-18 12:09:59,926][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 12:09:59,927][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 71, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '1',
  'fps_camera3': '2',
  'fps_camera4': '1',
  'fps_camera5': '1',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-18 12:09:59,928][0][INFO][generic_smbo.py:295] Iter 50, objectives: [inf, inf].
[2024-01-18 12:09:59,934][0][WARNING][history.py:651] No feasible observations! Return empty pareto.
