[2024-02-23 10:41:13,226][0][INFO][color_logger.py:203] Logfile: /data1/xiayuyang/online_mcmt/logs/0_2024-02-23-10-41-13-224010.log
[2024-02-23 10:41:13,400][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:13,550][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:13,699][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:13,848][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:13,995][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:14,132][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:14,271][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:14,408][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:14,545][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:14,681][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:14,818][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:14,958][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:15,096][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:15,234][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:15,371][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:15,508][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:15,646][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:15,788][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:15,926][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:16,064][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:16,202][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:16,339][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:16,480][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:16,618][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:16,760][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:16,898][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:17,036][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:17,174][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:17,315][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:17,453][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:17,591][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:17,733][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:17,872][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:18,010][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:18,149][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:18,287][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:18,428][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:18,566][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:18,704][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:18,842][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:18,980][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:19,118][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:19,260][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:19,398][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:19,536][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:19,674][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:19,812][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:19,950][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:20,089][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:20,227][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:20,368][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:20,507][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:20,646][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:20,784][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:20,923][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:21,062][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:21,201][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:21,339][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:21,477][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:21,619][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:21,758][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:21,896][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:22,034][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:41:22,173][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 10:45:35,207][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '320',
})

[2024-02-23 10:45:35,208][0][INFO][generic_smbo.py:295] Iter 1, objectives: [inf, inf].
[2024-02-23 10:47:08,224][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-23 10:47:08,225][0][INFO][generic_smbo.py:295] Iter 2, objectives: [inf, inf].
[2024-02-23 10:47:08,226][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-23 10:49:10,823][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-23 10:49:10,824][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-23 10:49:10,824][0][INFO][generic_smbo.py:295] Iter 3, objectives: [inf, inf].
[2024-02-23 10:49:10,825][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-23 10:51:13,514][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-23 10:51:13,515][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-23 10:51:13,516][0][INFO][generic_smbo.py:295] Iter 4, objectives: [inf, inf].
[2024-02-23 10:57:23,155][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-23 10:57:23,155][0][INFO][generic_smbo.py:295] Iter 5, objectives: [inf, inf].
[2024-02-23 10:58:30,522][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '320',
})

[2024-02-23 10:58:30,523][0][INFO][generic_smbo.py:295] Iter 6, objectives: [inf, inf].
[2024-02-23 10:58:30,523][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-23 11:04:46,494][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-23 11:04:46,495][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-23 11:04:46,495][0][INFO][generic_smbo.py:295] Iter 7, objectives: [inf, inf].
[2024-02-23 11:04:46,496][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-23 11:10:59,217][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-23 11:10:59,218][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-23 11:10:59,218][0][INFO][generic_smbo.py:295] Iter 8, objectives: [inf, inf].
[2024-02-23 11:10:59,219][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-23 11:17:11,062][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-23 11:17:11,063][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-23 11:17:11,063][0][INFO][generic_smbo.py:295] Iter 9, objectives: [inf, inf].
[2024-02-23 11:17:11,064][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 11:18:31,376][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '640',
})

[2024-02-23 11:18:31,377][0][INFO][generic_smbo.py:295] Iter 10, objectives: [inf, inf].
[2024-02-23 11:18:31,378][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-02-23 11:22:32,890][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-23 11:22:32,890][0][INFO][generic_smbo.py:295] Iter 11, objectives: [inf, inf].
[2024-02-23 11:22:32,892][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 11:25:42,143][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '640',
})

[2024-02-23 11:25:42,144][0][INFO][generic_smbo.py:295] Iter 12, objectives: [inf, inf].
[2024-02-23 11:25:42,146][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 11:27:14,028][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '1280',
})

[2024-02-23 11:27:14,029][0][INFO][generic_smbo.py:295] Iter 13, objectives: [inf, inf].
[2024-02-23 11:27:14,030][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-02-23 11:33:32,230][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '1280',
})

[2024-02-23 11:33:32,230][0][INFO][generic_smbo.py:295] Iter 14, objectives: [inf, inf].
[2024-02-23 11:33:32,231][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 11:35:29,135][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '640',
})

[2024-02-23 11:35:29,136][0][INFO][generic_smbo.py:295] Iter 15, objectives: [inf, inf].
[2024-02-23 11:35:29,137][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 11:37:13,629][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '640',
})

[2024-02-23 11:37:13,630][0][INFO][generic_smbo.py:295] Iter 16, objectives: [inf, inf].
[2024-02-23 11:37:13,631][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 11:43:13,334][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '1280',
})

[2024-02-23 11:43:13,335][0][INFO][generic_smbo.py:295] Iter 17, objectives: [inf, inf].
[2024-02-23 11:43:13,336][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 11:45:10,328][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '320',
})

[2024-02-23 11:45:10,329][0][INFO][generic_smbo.py:295] Iter 18, objectives: [inf, inf].
[2024-02-23 11:45:10,330][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 11:46:51,837][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '320',
})

[2024-02-23 11:46:51,838][0][INFO][generic_smbo.py:295] Iter 19, objectives: [inf, inf].
[2024-02-23 11:46:51,840][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 11:50:27,397][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '1280',
})

[2024-02-23 11:50:27,399][0][INFO][generic_smbo.py:295] Iter 20, objectives: [inf, inf].
[2024-02-23 11:50:27,400][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 11:51:43,411][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '320',
})

[2024-02-23 11:51:43,412][0][INFO][generic_smbo.py:295] Iter 21, objectives: [inf, inf].
[2024-02-23 11:52:03,958][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 11:54:05,945][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '320',
})

[2024-02-23 11:54:05,946][0][INFO][generic_smbo.py:295] Iter 22, objectives: [inf, inf].
[2024-02-23 11:54:05,947][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 11:56:13,834][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '640',
})

[2024-02-23 11:56:13,835][0][INFO][generic_smbo.py:295] Iter 23, objectives: [inf, inf].
[2024-02-23 11:56:13,837][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 11:59:14,881][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '640',
})

[2024-02-23 11:59:14,883][0][INFO][generic_smbo.py:295] Iter 24, objectives: [inf, inf].
[2024-02-23 11:59:14,884][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 12:02:20,121][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '320',
})

[2024-02-23 12:02:20,122][0][INFO][generic_smbo.py:295] Iter 25, objectives: [inf, inf].
[2024-02-23 12:02:20,124][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 12:04:20,826][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '640',
})

[2024-02-23 12:04:20,827][0][INFO][generic_smbo.py:295] Iter 26, objectives: [inf, inf].
[2024-02-23 12:04:20,829][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 12:07:34,359][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '320',
})

[2024-02-23 12:07:34,361][0][INFO][generic_smbo.py:295] Iter 27, objectives: [inf, inf].
[2024-02-23 12:07:34,363][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 12:09:43,230][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '1280',
})

[2024-02-23 12:09:43,232][0][INFO][generic_smbo.py:295] Iter 28, objectives: [inf, inf].
[2024-02-23 12:09:43,233][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 12:11:19,339][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '640',
})

[2024-02-23 12:11:19,340][0][INFO][generic_smbo.py:295] Iter 29, objectives: [inf, inf].
[2024-02-23 12:11:19,342][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 12:13:23,073][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '1280',
})

[2024-02-23 12:13:23,074][0][INFO][generic_smbo.py:295] Iter 30, objectives: [inf, inf].
[2024-02-23 12:13:23,076][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 12:18:42,731][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '640',
})

[2024-02-23 12:18:42,732][0][INFO][generic_smbo.py:295] Iter 31, objectives: [inf, inf].
[2024-02-23 12:18:42,733][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 12:20:55,766][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-23 12:20:55,767][0][INFO][generic_smbo.py:295] Iter 32, objectives: [inf, inf].
[2024-02-23 12:20:55,768][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 12:23:05,841][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '1280',
})

[2024-02-23 12:23:05,842][0][INFO][generic_smbo.py:295] Iter 33, objectives: [inf, inf].
[2024-02-23 12:23:05,844][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 12:25:38,552][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '320',
})

[2024-02-23 12:25:38,554][0][INFO][generic_smbo.py:295] Iter 34, objectives: [inf, inf].
[2024-02-23 12:25:38,555][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 12:29:03,247][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '640',
})

[2024-02-23 12:29:03,249][0][INFO][generic_smbo.py:295] Iter 35, objectives: [inf, inf].
[2024-02-23 12:29:03,251][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 12:34:33,444][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '320',
})

[2024-02-23 12:34:33,445][0][INFO][generic_smbo.py:295] Iter 36, objectives: [inf, inf].
[2024-02-23 12:34:33,445][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 12:37:57,482][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '1280',
})

[2024-02-23 12:37:57,484][0][INFO][generic_smbo.py:295] Iter 37, objectives: [inf, inf].
[2024-02-23 12:37:57,486][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 12:43:37,601][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '640',
})

[2024-02-23 12:43:37,602][0][INFO][generic_smbo.py:295] Iter 38, objectives: [inf, inf].
[2024-02-23 12:43:37,603][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 12:49:49,018][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '640',
})

[2024-02-23 12:49:49,019][0][INFO][generic_smbo.py:295] Iter 39, objectives: [inf, inf].
[2024-02-23 12:49:49,020][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 12:55:42,235][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '320',
})

[2024-02-23 12:55:42,236][0][INFO][generic_smbo.py:295] Iter 40, objectives: [inf, inf].
[2024-02-23 12:55:42,237][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 12:57:43,831][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '320',
})

[2024-02-23 12:57:43,832][0][INFO][generic_smbo.py:295] Iter 41, objectives: [inf, inf].
[2024-02-23 12:57:43,834][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 12:57:43,987][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 12:57:43,987][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '1280',
})

[2024-02-23 12:59:53,047][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '1280',
})

[2024-02-23 12:59:53,049][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-23 12:59:53,049][0][INFO][generic_smbo.py:295] Iter 42, objectives: [inf, inf].
[2024-02-23 12:59:53,051][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 12:59:53,198][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 12:59:53,198][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '640',
})

[2024-02-23 13:03:03,318][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '640',
})

[2024-02-23 13:03:03,319][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-23 13:03:03,319][0][INFO][generic_smbo.py:295] Iter 43, objectives: [inf, inf].
[2024-02-23 13:03:03,320][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 13:03:03,466][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 13:03:03,466][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '320',
})

[2024-02-23 13:08:33,960][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '320',
})

[2024-02-23 13:08:33,961][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-23 13:08:33,961][0][INFO][generic_smbo.py:295] Iter 44, objectives: [inf, inf].
[2024-02-23 13:08:33,962][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 13:08:34,092][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 13:08:34,092][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '640',
})

[2024-02-23 13:09:49,200][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '10',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '640',
})

[2024-02-23 13:09:49,200][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-23 13:09:49,200][0][INFO][generic_smbo.py:295] Iter 45, objectives: [inf, inf].
[2024-02-23 13:09:49,201][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 13:09:49,357][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 13:09:49,357][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '1280',
})

[2024-02-23 13:13:33,640][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5s.pt',
  'resolution_camera': '1280',
})

[2024-02-23 13:13:33,642][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-23 13:13:33,642][0][INFO][generic_smbo.py:295] Iter 46, objectives: [inf, inf].
[2024-02-23 13:13:33,644][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 13:13:33,788][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 13:13:33,789][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '320',
})

[2024-02-23 13:16:38,134][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '2',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '320',
})

[2024-02-23 13:16:38,135][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-23 13:16:38,135][0][INFO][generic_smbo.py:295] Iter 47, objectives: [inf, inf].
[2024-02-23 13:16:38,136][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 13:16:38,279][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 13:16:38,280][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '640',
})

[2024-02-23 13:22:47,119][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '640',
})

[2024-02-23 13:22:47,119][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-23 13:22:47,120][0][INFO][generic_smbo.py:295] Iter 48, objectives: [inf, inf].
[2024-02-23 13:22:47,121][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 13:22:47,267][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 13:22:47,268][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-23 13:29:01,589][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '1',
  'model_size_camera': 'yolov5l.pt',
  'resolution_camera': '1280',
})

[2024-02-23 13:29:01,590][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-23 13:29:01,591][0][INFO][generic_smbo.py:295] Iter 49, objectives: [inf, inf].
[2024-02-23 13:29:01,592][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-02-23 13:29:01,741][0][WARNING][generic_advisor.py:482] Cannot sample non duplicate configuration after 1000 iterations.
[2024-02-23 13:29:01,741][0][WARNING][generic_smbo.py:253] Evaluating duplicated configuration: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '320',
})

[2024-02-23 13:30:58,529][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/s_bo.py", line 85, in multi_camera_matching
    accuracy, processing_time, section_json = accuracy, processing_time = profile(target_cam_=1, cams_dir_= cams_dir,
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtsc.py", line 795, in profile
    for frame, frame_data in mm_data[cam].items():
KeyError: 'c004'

config: Configuration(values={
  'fps_camera': '4',
  'model_size_camera': 'yolov5m.pt',
  'resolution_camera': '320',
})

[2024-02-23 13:30:58,531][0][WARNING][history.py:242] Duplicate configuration detected!
[2024-02-23 13:30:58,531][0][INFO][generic_smbo.py:295] Iter 50, objectives: [inf, inf].
[2024-02-23 13:30:58,539][0][WARNING][history.py:651] No feasible observations! Return empty pareto.
