[2024-01-23 22:52:29,926][0][INFO][color_logger.py:203] Logfile: /data1/xiayuyang/online_mcmt/logs/0_2024-01-23-22-52-29-924735.log
[2024-01-23 22:53:00,538][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 910, in profile
    gt_detect, gt_dict, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 792, in run_mtmc
    g_tid += 1
UnboundLocalError: local variable 'g_tid' referenced before assignment

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '1',
  'fps_camera3': '1',
  'fps_camera4': '1',
  'fps_camera5': '1',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-23 22:53:00,540][0][INFO][generic_smbo.py:295] Iter 1, objectives: [inf, inf].
[2024-01-23 22:53:24,607][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 910, in profile
    gt_detect, gt_dict, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 792, in run_mtmc
    g_tid += 1
UnboundLocalError: local variable 'g_tid' referenced before assignment

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '10',
  'fps_camera3': '4',
  'fps_camera4': '10',
  'fps_camera5': '4',
  'lazy_threshold': 0.82,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '1280',
  'resolution_camera5': '640',
})

[2024-01-23 22:53:24,609][0][INFO][generic_smbo.py:295] Iter 2, objectives: [inf, inf].
[2024-01-23 22:53:56,759][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 910, in profile
    gt_detect, gt_dict, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 792, in run_mtmc
    g_tid += 1
UnboundLocalError: local variable 'g_tid' referenced before assignment

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '10',
  'fps_camera3': '1',
  'fps_camera4': '1',
  'fps_camera5': '10',
  'lazy_threshold': 0.78,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-23 22:53:56,760][0][INFO][generic_smbo.py:295] Iter 3, objectives: [inf, inf].
[2024-01-23 22:54:22,641][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 910, in profile
    gt_detect, gt_dict, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 792, in run_mtmc
    g_tid += 1
UnboundLocalError: local variable 'g_tid' referenced before assignment

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '1',
  'fps_camera3': '10',
  'fps_camera4': '10',
  'fps_camera5': '1',
  'lazy_threshold': 0.8999999999999999,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-23 22:54:22,642][0][INFO][generic_smbo.py:295] Iter 4, objectives: [inf, inf].
[2024-01-23 22:54:53,215][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 910, in profile
    gt_detect, gt_dict, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 792, in run_mtmc
    g_tid += 1
UnboundLocalError: local variable 'g_tid' referenced before assignment

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '10',
  'fps_camera3': '1',
  'fps_camera4': '10',
  'fps_camera5': '1',
  'lazy_threshold': 0.82,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-23 22:54:53,217][0][INFO][generic_smbo.py:295] Iter 5, objectives: [inf, inf].
[2024-01-23 22:55:25,344][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 910, in profile
    gt_detect, gt_dict, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 792, in run_mtmc
    g_tid += 1
UnboundLocalError: local variable 'g_tid' referenced before assignment

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '1',
  'fps_camera3': '2',
  'fps_camera4': '2',
  'fps_camera5': '1',
  'lazy_threshold': 0.62,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '320',
})

[2024-01-23 22:55:25,345][0][INFO][generic_smbo.py:295] Iter 6, objectives: [inf, inf].
[2024-01-23 22:55:51,609][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 910, in profile
    gt_detect, gt_dict, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 792, in run_mtmc
    g_tid += 1
UnboundLocalError: local variable 'g_tid' referenced before assignment

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '1',
  'fps_camera3': '1',
  'fps_camera4': '10',
  'fps_camera5': '2',
  'lazy_threshold': 0.82,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '320',
})

[2024-01-23 22:55:51,611][0][INFO][generic_smbo.py:295] Iter 7, objectives: [inf, inf].
[2024-01-23 22:56:24,950][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 910, in profile
    gt_detect, gt_dict, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 792, in run_mtmc
    g_tid += 1
UnboundLocalError: local variable 'g_tid' referenced before assignment

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '4',
  'fps_camera3': '2',
  'fps_camera4': '4',
  'fps_camera5': '4',
  'lazy_threshold': 0.76,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-23 22:56:24,951][0][INFO][generic_smbo.py:295] Iter 8, objectives: [inf, inf].
[2024-01-23 22:57:00,905][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 910, in profile
    gt_detect, gt_dict, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 792, in run_mtmc
    g_tid += 1
UnboundLocalError: local variable 'g_tid' referenced before assignment

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '1',
  'fps_camera3': '1',
  'fps_camera4': '1',
  'fps_camera5': '10',
  'lazy_threshold': 0.72,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '640',
  'resolution_camera3': '1280',
  'resolution_camera4': '640',
  'resolution_camera5': '1280',
})

[2024-01-23 22:57:00,906][0][INFO][generic_smbo.py:295] Iter 9, objectives: [inf, inf].
[2024-01-23 22:57:00,909][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:57:47,027][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 910, in profile
    gt_detect, gt_dict, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 792, in run_mtmc
    g_tid += 1
UnboundLocalError: local variable 'g_tid' referenced before assignment

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '10',
  'fps_camera3': '1',
  'fps_camera4': '1',
  'fps_camera5': '10',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '640',
  'resolution_camera3': '640',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-23 22:57:47,028][0][INFO][generic_smbo.py:295] Iter 10, objectives: [inf, inf].
[2024-01-23 22:57:47,030][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:58:06,827][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 910, in profile
    gt_detect, gt_dict, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 792, in run_mtmc
    g_tid += 1
UnboundLocalError: local variable 'g_tid' referenced before assignment

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '10',
  'fps_camera3': '4',
  'fps_camera4': '10',
  'fps_camera5': '2',
  'lazy_threshold': 0.6599999999999999,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-23 22:58:06,828][0][INFO][generic_smbo.py:295] Iter 11, objectives: [inf, inf].
[2024-01-23 22:58:06,830][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:58:30,155][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 910, in profile
    gt_detect, gt_dict, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 792, in run_mtmc
    g_tid += 1
UnboundLocalError: local variable 'g_tid' referenced before assignment

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '4',
  'fps_camera3': '2',
  'fps_camera4': '2',
  'fps_camera5': '4',
  'lazy_threshold': 0.78,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-23 22:58:30,156][0][INFO][generic_smbo.py:295] Iter 12, objectives: [inf, inf].
[2024-01-23 22:58:30,157][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:59:02,035][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 910, in profile
    gt_detect, gt_dict, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 792, in run_mtmc
    g_tid += 1
UnboundLocalError: local variable 'g_tid' referenced before assignment

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '1',
  'fps_camera3': '10',
  'fps_camera4': '10',
  'fps_camera5': '2',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-23 22:59:02,037][0][INFO][generic_smbo.py:295] Iter 13, objectives: [inf, inf].
[2024-01-23 22:59:02,039][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:59:32,482][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 910, in profile
    gt_detect, gt_dict, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 792, in run_mtmc
    g_tid += 1
UnboundLocalError: local variable 'g_tid' referenced before assignment

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '1',
  'fps_camera3': '2',
  'fps_camera4': '2',
  'fps_camera5': '4',
  'lazy_threshold': 0.78,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-23 22:59:32,483][0][INFO][generic_smbo.py:295] Iter 14, objectives: [inf, inf].
[2024-01-23 22:59:32,486][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:59:59,045][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 910, in profile
    gt_detect, gt_dict, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 792, in run_mtmc
    g_tid += 1
UnboundLocalError: local variable 'g_tid' referenced before assignment

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '2',
  'fps_camera3': '2',
  'fps_camera4': '2',
  'fps_camera5': '1',
  'lazy_threshold': 0.8,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '640',
  'resolution_camera5': '1280',
})

[2024-01-23 22:59:59,046][0][INFO][generic_smbo.py:295] Iter 15, objectives: [inf, inf].
[2024-01-23 22:59:59,047][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-01-23 23:00:29,865][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 910, in profile
    gt_detect, gt_dict, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 792, in run_mtmc
    g_tid += 1
UnboundLocalError: local variable 'g_tid' referenced before assignment

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '10',
  'fps_camera3': '1',
  'fps_camera4': '4',
  'fps_camera5': '1',
  'lazy_threshold': 0.6599999999999999,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '640',
  'resolution_camera3': '640',
  'resolution_camera4': '1280',
  'resolution_camera5': '640',
})

[2024-01-23 23:00:29,866][0][INFO][generic_smbo.py:295] Iter 16, objectives: [inf, inf].
[2024-01-23 23:00:29,868][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-01-23 23:00:59,843][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 910, in profile
    gt_detect, gt_dict, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 792, in run_mtmc
    g_tid += 1
UnboundLocalError: local variable 'g_tid' referenced before assignment

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '1',
  'fps_camera3': '2',
  'fps_camera4': '10',
  'fps_camera5': '10',
  'lazy_threshold': 0.72,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '1280',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-23 23:00:59,844][0][INFO][generic_smbo.py:295] Iter 17, objectives: [inf, inf].
[2024-01-23 23:00:59,846][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
