[2024-01-23 20:56:04,399][0][INFO][color_logger.py:203] Logfile: /data1/xiayuyang/online_mcmt/logs/0_2024-01-23-20-56-04-398521.log
[2024-01-23 21:21:46,096][0][INFO][generic_smbo.py:295] Iter 1, objectives: [0.8290789129230407, 0.0053068713015980195].
[2024-01-23 21:29:16,642][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 910, in profile
    precision, recall, f1 = mot_metrics(gt_detect[cam], gt_dict[cam])
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 406, in mot_metrics
    f1_score = 200 * recall * precision / (precision + recall)
ZeroDivisionError: float division by zero

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '10',
  'fps_camera3': '10',
  'fps_camera4': '10',
  'fps_camera5': '4',
  'lazy_threshold': 0.8999999999999999,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '640',
  'resolution_camera3': '640',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-23 21:29:16,642][0][INFO][generic_smbo.py:295] Iter 2, objectives: [inf, inf].
[2024-01-23 21:29:36,087][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 902, in profile
    gt_detect, gt_dict, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 791, in run_mtmc
    gt_detect[cam][matched_tid] = {}
UnboundLocalError: local variable 'matched_tid' referenced before assignment

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '4',
  'fps_camera3': '10',
  'fps_camera4': '1',
  'fps_camera5': '10',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '320',
  'resolution_camera5': '640',
})

[2024-01-23 21:29:36,088][0][INFO][generic_smbo.py:295] Iter 3, objectives: [inf, inf].
[2024-01-23 21:56:49,091][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 910, in profile
    precision, recall, f1 = mot_metrics(gt_detect[cam], gt_dict[cam])
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 406, in mot_metrics
    f1_score = 200 * recall * precision / (precision + recall)
ZeroDivisionError: float division by zero

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '1',
  'fps_camera3': '2',
  'fps_camera4': '1',
  'fps_camera5': '4',
  'lazy_threshold': 0.6799999999999999,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-23 21:56:49,092][0][INFO][generic_smbo.py:295] Iter 4, objectives: [inf, inf].
[2024-01-23 21:57:09,939][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 902, in profile
    gt_detect, gt_dict, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 791, in run_mtmc
    gt_detect[cam][matched_tid] = {}
UnboundLocalError: local variable 'matched_tid' referenced before assignment

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '1',
  'fps_camera3': '10',
  'fps_camera4': '10',
  'fps_camera5': '1',
  'lazy_threshold': 0.88,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-23 21:57:09,940][0][INFO][generic_smbo.py:295] Iter 5, objectives: [inf, inf].
