[2024-01-18 11:49:48,782][0][INFO][color_logger.py:203] Logfile: /data1/xiayuyang/online_mcmt/logs/0_2024-01-18-11-49-48-782655.log
[2024-01-18 11:49:48,855][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '1',
  'fps_camera3': '1',
  'fps_camera4': '1',
  'fps_camera5': '1',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-18 11:49:48,855][0][INFO][generic_smbo.py:295] Iter 1, objectives: [inf, inf].
[2024-01-18 11:49:48,855][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '10',
  'fps_camera3': '10',
  'fps_camera4': '10',
  'fps_camera5': '4',
  'lazy_threshold': 0.74,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '320',
})

[2024-01-18 11:49:48,856][0][INFO][generic_smbo.py:295] Iter 2, objectives: [inf, inf].
[2024-01-18 11:49:48,856][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '2',
  'fps_camera3': '10',
  'fps_camera4': '1',
  'fps_camera5': '1',
  'lazy_threshold': 0.8999999999999999,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '640',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-18 11:49:48,856][0][INFO][generic_smbo.py:295] Iter 3, objectives: [inf, inf].
[2024-01-18 11:49:48,857][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '1',
  'fps_camera3': '10',
  'fps_camera4': '1',
  'fps_camera5': '10',
  'lazy_threshold': 0.72,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '1280',
  'resolution_camera5': '320',
})

[2024-01-18 11:49:48,857][0][INFO][generic_smbo.py:295] Iter 4, objectives: [inf, inf].
[2024-01-18 11:49:48,857][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '10',
  'fps_camera3': '1',
  'fps_camera4': '10',
  'fps_camera5': '2',
  'lazy_threshold': 0.82,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '640',
  'resolution_camera5': '1280',
})

[2024-01-18 11:49:48,858][0][INFO][generic_smbo.py:295] Iter 5, objectives: [inf, inf].
[2024-01-18 11:49:48,858][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '1',
  'fps_camera3': '10',
  'fps_camera4': '10',
  'fps_camera5': '2',
  'lazy_threshold': 0.72,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '640',
  'resolution_camera5': '640',
})

[2024-01-18 11:49:48,858][0][INFO][generic_smbo.py:295] Iter 6, objectives: [inf, inf].
[2024-01-18 11:49:48,859][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '10',
  'fps_camera3': '2',
  'fps_camera4': '1',
  'fps_camera5': '1',
  'lazy_threshold': 0.72,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '320',
})

[2024-01-18 11:49:48,859][0][INFO][generic_smbo.py:295] Iter 7, objectives: [inf, inf].
[2024-01-18 11:49:48,859][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '1',
  'fps_camera3': '1',
  'fps_camera4': '1',
  'fps_camera5': '10',
  'lazy_threshold': 0.6599999999999999,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '320',
})

[2024-01-18 11:49:48,860][0][INFO][generic_smbo.py:295] Iter 8, objectives: [inf, inf].
[2024-01-18 11:49:48,860][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '1',
  'fps_camera3': '4',
  'fps_camera4': '10',
  'fps_camera5': '1',
  'lazy_threshold': 0.64,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '640',
  'resolution_camera3': '320',
  'resolution_camera4': '640',
  'resolution_camera5': '320',
})

[2024-01-18 11:49:48,860][0][INFO][generic_smbo.py:295] Iter 9, objectives: [inf, inf].
[2024-01-18 11:49:48,861][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:48,862][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '1',
  'fps_camera3': '1',
  'fps_camera4': '2',
  'fps_camera5': '4',
  'lazy_threshold': 0.72,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '640',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '320',
})

[2024-01-18 11:49:48,863][0][INFO][generic_smbo.py:295] Iter 10, objectives: [inf, inf].
[2024-01-18 11:49:48,863][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:48,864][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '10',
  'fps_camera3': '2',
  'fps_camera4': '1',
  'fps_camera5': '1',
  'lazy_threshold': 0.62,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '640',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-18 11:49:48,864][0][INFO][generic_smbo.py:295] Iter 11, objectives: [inf, inf].
[2024-01-18 11:49:48,865][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:48,866][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '1',
  'fps_camera3': '2',
  'fps_camera4': '2',
  'fps_camera5': '1',
  'lazy_threshold': 0.86,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '640',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '640',
})

[2024-01-18 11:49:48,866][0][INFO][generic_smbo.py:295] Iter 12, objectives: [inf, inf].
[2024-01-18 11:49:48,866][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-01-18 11:49:48,867][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '4',
  'fps_camera3': '1',
  'fps_camera4': '4',
  'fps_camera5': '2',
  'lazy_threshold': 0.8,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-18 11:49:48,868][0][INFO][generic_smbo.py:295] Iter 13, objectives: [inf, inf].
[2024-01-18 11:49:48,868][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-01-18 11:49:48,869][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '2',
  'fps_camera3': '1',
  'fps_camera4': '10',
  'fps_camera5': '4',
  'lazy_threshold': 0.8999999999999999,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '640',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '640',
})

[2024-01-18 11:49:48,869][0][INFO][generic_smbo.py:295] Iter 14, objectives: [inf, inf].
[2024-01-18 11:49:48,870][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:48,871][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '4',
  'fps_camera3': '1',
  'fps_camera4': '1',
  'fps_camera5': '4',
  'lazy_threshold': 0.8,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-18 11:49:48,871][0][INFO][generic_smbo.py:295] Iter 15, objectives: [inf, inf].
[2024-01-18 11:49:48,872][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:48,873][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '1',
  'fps_camera3': '4',
  'fps_camera4': '4',
  'fps_camera5': '1',
  'lazy_threshold': 0.84,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '640',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-18 11:49:48,873][0][INFO][generic_smbo.py:295] Iter 16, objectives: [inf, inf].
[2024-01-18 11:49:48,874][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:48,875][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '4',
  'fps_camera3': '4',
  'fps_camera4': '1',
  'fps_camera5': '10',
  'lazy_threshold': 0.88,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '640',
  'resolution_camera5': '320',
})

[2024-01-18 11:49:48,875][0][INFO][generic_smbo.py:295] Iter 17, objectives: [inf, inf].
[2024-01-18 11:49:48,876][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:48,877][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '4',
  'fps_camera3': '4',
  'fps_camera4': '2',
  'fps_camera5': '2',
  'lazy_threshold': 0.84,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '640',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-18 11:49:48,877][0][INFO][generic_smbo.py:295] Iter 18, objectives: [inf, inf].
[2024-01-18 11:49:48,878][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-01-18 11:49:48,878][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '2',
  'fps_camera3': '1',
  'fps_camera4': '2',
  'fps_camera5': '4',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '320',
})

[2024-01-18 11:49:48,879][0][INFO][generic_smbo.py:295] Iter 19, objectives: [inf, inf].
[2024-01-18 11:49:48,879][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:48,880][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '4',
  'fps_camera3': '10',
  'fps_camera4': '4',
  'fps_camera5': '1',
  'lazy_threshold': 0.72,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '640',
  'resolution_camera3': '1280',
  'resolution_camera4': '640',
  'resolution_camera5': '320',
})

[2024-01-18 11:49:48,881][0][INFO][generic_smbo.py:295] Iter 20, objectives: [inf, inf].
[2024-01-18 11:49:48,881][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:48,883][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '1',
  'fps_camera3': '4',
  'fps_camera4': '1',
  'fps_camera5': '4',
  'lazy_threshold': 0.76,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '640',
})

[2024-01-18 11:49:48,883][0][INFO][generic_smbo.py:295] Iter 21, objectives: [inf, inf].
[2024-01-18 11:49:48,883][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-01-18 11:49:48,884][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '2',
  'fps_camera3': '2',
  'fps_camera4': '2',
  'fps_camera5': '1',
  'lazy_threshold': 0.6799999999999999,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '640',
})

[2024-01-18 11:49:48,884][0][INFO][generic_smbo.py:295] Iter 22, objectives: [inf, inf].
[2024-01-18 11:49:48,885][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:49,103][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '2',
  'fps_camera3': '2',
  'fps_camera4': '10',
  'fps_camera5': '1',
  'lazy_threshold': 0.8,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-18 11:49:49,103][0][INFO][generic_smbo.py:295] Iter 23, objectives: [inf, inf].
[2024-01-18 11:49:49,104][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:49,105][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '1',
  'fps_camera3': '10',
  'fps_camera4': '1',
  'fps_camera5': '1',
  'lazy_threshold': 0.64,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '640',
  'resolution_camera4': '1280',
  'resolution_camera5': '640',
})

[2024-01-18 11:49:49,105][0][INFO][generic_smbo.py:295] Iter 24, objectives: [inf, inf].
[2024-01-18 11:49:49,106][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:49,107][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '2',
  'fps_camera3': '2',
  'fps_camera4': '1',
  'fps_camera5': '1',
  'lazy_threshold': 0.62,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '640',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '640',
})

[2024-01-18 11:49:49,107][0][INFO][generic_smbo.py:295] Iter 25, objectives: [inf, inf].
[2024-01-18 11:49:49,108][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:49,109][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '2',
  'fps_camera3': '4',
  'fps_camera4': '10',
  'fps_camera5': '1',
  'lazy_threshold': 0.62,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '640',
  'resolution_camera3': '1280',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-18 11:49:49,109][0][INFO][generic_smbo.py:295] Iter 26, objectives: [inf, inf].
[2024-01-18 11:49:49,110][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:49,111][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '10',
  'fps_camera3': '1',
  'fps_camera4': '1',
  'fps_camera5': '4',
  'lazy_threshold': 0.62,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '640',
  'resolution_camera5': '1280',
})

[2024-01-18 11:49:49,111][0][INFO][generic_smbo.py:295] Iter 27, objectives: [inf, inf].
[2024-01-18 11:49:49,112][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:49,113][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '2',
  'fps_camera3': '1',
  'fps_camera4': '4',
  'fps_camera5': '2',
  'lazy_threshold': 0.84,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '640',
  'resolution_camera5': '320',
})

[2024-01-18 11:49:49,116][0][INFO][generic_smbo.py:295] Iter 28, objectives: [inf, inf].
[2024-01-18 11:49:49,117][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-01-18 11:49:49,118][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '4',
  'fps_camera3': '10',
  'fps_camera4': '1',
  'fps_camera5': '1',
  'lazy_threshold': 0.72,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '640',
})

[2024-01-18 11:49:49,118][0][INFO][generic_smbo.py:295] Iter 29, objectives: [inf, inf].
[2024-01-18 11:49:49,119][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:49,120][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '1',
  'fps_camera3': '1',
  'fps_camera4': '10',
  'fps_camera5': '10',
  'lazy_threshold': 0.84,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '640',
})

[2024-01-18 11:49:49,120][0][INFO][generic_smbo.py:295] Iter 30, objectives: [inf, inf].
[2024-01-18 11:49:49,121][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:49,122][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '4',
  'fps_camera3': '1',
  'fps_camera4': '2',
  'fps_camera5': '10',
  'lazy_threshold': 0.8,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '320',
  'resolution_camera5': '640',
})

[2024-01-18 11:49:49,122][0][INFO][generic_smbo.py:295] Iter 31, objectives: [inf, inf].
[2024-01-18 11:49:49,123][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:49,124][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '4',
  'fps_camera3': '10',
  'fps_camera4': '10',
  'fps_camera5': '1',
  'lazy_threshold': 0.8999999999999999,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-18 11:49:49,125][0][INFO][generic_smbo.py:295] Iter 32, objectives: [inf, inf].
[2024-01-18 11:49:49,125][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:49,126][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '1',
  'fps_camera3': '1',
  'fps_camera4': '1',
  'fps_camera5': '4',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '640',
  'resolution_camera4': '1280',
  'resolution_camera5': '320',
})

[2024-01-18 11:49:49,127][0][INFO][generic_smbo.py:295] Iter 33, objectives: [inf, inf].
[2024-01-18 11:49:49,127][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:49,129][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '4',
  'fps_camera3': '2',
  'fps_camera4': '2',
  'fps_camera5': '10',
  'lazy_threshold': 0.8999999999999999,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '640',
  'resolution_camera4': '640',
  'resolution_camera5': '1280',
})

[2024-01-18 11:49:49,129][0][INFO][generic_smbo.py:295] Iter 34, objectives: [inf, inf].
[2024-01-18 11:49:49,130][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:49,131][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '10',
  'fps_camera3': '4',
  'fps_camera4': '10',
  'fps_camera5': '10',
  'lazy_threshold': 0.6599999999999999,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-18 11:49:49,131][0][INFO][generic_smbo.py:295] Iter 35, objectives: [inf, inf].
[2024-01-18 11:49:49,132][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:49,133][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '2',
  'fps_camera3': '2',
  'fps_camera4': '1',
  'fps_camera5': '2',
  'lazy_threshold': 0.84,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-18 11:49:49,133][0][INFO][generic_smbo.py:295] Iter 36, objectives: [inf, inf].
[2024-01-18 11:49:49,134][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:49,135][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '2',
  'fps_camera3': '2',
  'fps_camera4': '2',
  'fps_camera5': '10',
  'lazy_threshold': 0.6599999999999999,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '640',
  'resolution_camera5': '640',
})

[2024-01-18 11:49:49,135][0][INFO][generic_smbo.py:295] Iter 37, objectives: [inf, inf].
[2024-01-18 11:49:49,136][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:49,137][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '10',
  'fps_camera3': '10',
  'fps_camera4': '2',
  'fps_camera5': '2',
  'lazy_threshold': 0.8999999999999999,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-18 11:49:49,138][0][INFO][generic_smbo.py:295] Iter 38, objectives: [inf, inf].
[2024-01-18 11:49:49,138][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-01-18 11:49:49,139][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '4',
  'fps_camera3': '10',
  'fps_camera4': '4',
  'fps_camera5': '4',
  'lazy_threshold': 0.78,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '640',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-18 11:49:49,139][0][INFO][generic_smbo.py:295] Iter 39, objectives: [inf, inf].
[2024-01-18 11:49:49,140][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:49,141][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '10',
  'fps_camera3': '1',
  'fps_camera4': '2',
  'fps_camera5': '4',
  'lazy_threshold': 0.88,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '640',
  'resolution_camera5': '1280',
})

[2024-01-18 11:49:49,142][0][INFO][generic_smbo.py:295] Iter 40, objectives: [inf, inf].
[2024-01-18 11:49:49,142][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:49,143][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '2',
  'fps_camera3': '10',
  'fps_camera4': '1',
  'fps_camera5': '4',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '640',
  'resolution_camera3': '1280',
  'resolution_camera4': '640',
  'resolution_camera5': '1280',
})

[2024-01-18 11:49:49,144][0][INFO][generic_smbo.py:295] Iter 41, objectives: [inf, inf].
[2024-01-18 11:49:49,144][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:49,146][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '1',
  'fps_camera3': '2',
  'fps_camera4': '2',
  'fps_camera5': '2',
  'lazy_threshold': 0.8999999999999999,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '640',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-18 11:49:49,146][0][INFO][generic_smbo.py:295] Iter 42, objectives: [inf, inf].
[2024-01-18 11:49:49,147][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:49,148][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '10',
  'fps_camera3': '2',
  'fps_camera4': '1',
  'fps_camera5': '1',
  'lazy_threshold': 0.74,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '640',
  'resolution_camera5': '640',
})

[2024-01-18 11:49:49,148][0][INFO][generic_smbo.py:295] Iter 43, objectives: [inf, inf].
[2024-01-18 11:49:49,149][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:49,150][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '10',
  'fps_camera3': '1',
  'fps_camera4': '2',
  'fps_camera5': '2',
  'lazy_threshold': 0.74,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '640',
})

[2024-01-18 11:49:49,150][0][INFO][generic_smbo.py:295] Iter 44, objectives: [inf, inf].
[2024-01-18 11:49:49,151][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:49,152][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '10',
  'fps_camera3': '2',
  'fps_camera4': '2',
  'fps_camera5': '10',
  'lazy_threshold': 0.74,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-18 11:49:49,152][0][INFO][generic_smbo.py:295] Iter 45, objectives: [inf, inf].
[2024-01-18 11:49:49,153][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:49,154][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '4',
  'fps_camera3': '1',
  'fps_camera4': '2',
  'fps_camera5': '10',
  'lazy_threshold': 0.8,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-18 11:49:49,155][0][INFO][generic_smbo.py:295] Iter 46, objectives: [inf, inf].
[2024-01-18 11:49:49,155][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:49,156][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '1',
  'fps_camera3': '4',
  'fps_camera4': '2',
  'fps_camera5': '4',
  'lazy_threshold': 0.8,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '320',
})

[2024-01-18 11:49:49,157][0][INFO][generic_smbo.py:295] Iter 47, objectives: [inf, inf].
[2024-01-18 11:49:49,157][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:49,159][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '1',
  'fps_camera3': '4',
  'fps_camera4': '1',
  'fps_camera5': '1',
  'lazy_threshold': 0.6,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '640',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-18 11:49:49,159][0][INFO][generic_smbo.py:295] Iter 48, objectives: [inf, inf].
[2024-01-18 11:49:49,160][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:49,161][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '4',
  'fps_camera3': '2',
  'fps_camera4': '4',
  'fps_camera5': '2',
  'lazy_threshold': 0.8,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '320',
})

[2024-01-18 11:49:49,161][0][INFO][generic_smbo.py:295] Iter 49, objectives: [inf, inf].
[2024-01-18 11:49:49,162][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-18 11:49:49,163][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/miniconda3/envs/videoDB/lib/python3.7/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 70, in multi_camera_matching
    cams_dir_= cams_dir, weights_= weights, imgsz_=imgsz, cams_ratio_=cams_ratio, lazy_threshold_=lazy_threshold, gpu_id = GPU_ID)
TypeError: profile() got an unexpected keyword argument 'gpu_id'

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '1',
  'fps_camera3': '10',
  'fps_camera4': '2',
  'fps_camera5': '10',
  'lazy_threshold': 0.78,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-18 11:49:49,164][0][INFO][generic_smbo.py:295] Iter 50, objectives: [inf, inf].
[2024-01-18 11:49:49,169][0][WARNING][history.py:651] No feasible observations! Return empty pareto.
