[2024-03-28 22:32:40,425][0][INFO][color_logger.py:203] Logfile: /data1/xiayuyang/online_mcmt/logs/0_2024-03-28-22-32-40-425486.log
[2024-03-28 22:33:40,967][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_bo.py", line 103, in multi_camera_matching
    accuracy, processing_time, section_json = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 862, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 815, in run_mtmc
    mm_data[cam][i]['detections'].append([matched_tid,x,y,w,h])
KeyError: 190

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '1',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
})

[2024-03-28 22:33:40,968][0][INFO][generic_smbo.py:295] Iter 1, objectives: [inf, inf].
[2024-03-28 22:34:06,232][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_bo.py", line 103, in multi_camera_matching
    accuracy, processing_time, section_json = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 862, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 815, in run_mtmc
    mm_data[cam][i]['detections'].append([matched_tid,x,y,w,h])
KeyError: 100

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '5',
  'lazy_threshold': 0.82,
  'model_size_camera1': 'yolov5x.pt',
  'model_size_camera2': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
})

[2024-03-28 22:34:06,233][0][INFO][generic_smbo.py:295] Iter 2, objectives: [inf, inf].
[2024-03-28 22:34:38,301][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_bo.py", line 103, in multi_camera_matching
    accuracy, processing_time, section_json = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 862, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 815, in run_mtmc
    mm_data[cam][i]['detections'].append([matched_tid,x,y,w,h])
KeyError: 95

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '10',
  'lazy_threshold': 0.6599999999999999,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5x.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '960',
})

[2024-03-28 22:34:38,302][0][INFO][generic_smbo.py:295] Iter 3, objectives: [inf, inf].
[2024-03-28 22:35:46,399][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_bo.py", line 103, in multi_camera_matching
    accuracy, processing_time, section_json = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 862, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 815, in run_mtmc
    mm_data[cam][i]['detections'].append([matched_tid,x,y,w,h])
KeyError: 191

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '1',
  'lazy_threshold': 0.76,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5x.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '960',
})

[2024-03-28 22:35:46,400][0][INFO][generic_smbo.py:295] Iter 4, objectives: [inf, inf].
[2024-03-28 22:36:07,003][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_bo.py", line 103, in multi_camera_matching
    accuracy, processing_time, section_json = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 862, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 815, in run_mtmc
    mm_data[cam][i]['detections'].append([matched_tid,x,y,w,h])
KeyError: 95

config: Configuration(values={
  'fps_camera1': '5',
  'fps_camera2': '5',
  'lazy_threshold': 0.64,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '320',
})

[2024-03-28 22:36:07,004][0][INFO][generic_smbo.py:295] Iter 5, objectives: [inf, inf].
[2024-03-28 22:36:29,502][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_bo.py", line 103, in multi_camera_matching
    accuracy, processing_time, section_json = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 862, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 815, in run_mtmc
    mm_data[cam][i]['detections'].append([matched_tid,x,y,w,h])
KeyError: 190

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '10',
  'lazy_threshold': 0.6599999999999999,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '480',
})

[2024-03-28 22:36:29,503][0][INFO][generic_smbo.py:295] Iter 6, objectives: [inf, inf].
[2024-03-28 22:36:44,931][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_bo.py", line 103, in multi_camera_matching
    accuracy, processing_time, section_json = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 862, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 815, in run_mtmc
    mm_data[cam][i]['detections'].append([matched_tid,x,y,w,h])
KeyError: 2

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '1',
  'lazy_threshold': 0.86,
  'model_size_camera1': 'yolov5x.pt',
  'model_size_camera2': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '960',
})

[2024-03-28 22:36:44,932][0][INFO][generic_smbo.py:295] Iter 7, objectives: [inf, inf].
[2024-03-28 22:37:08,962][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_bo.py", line 103, in multi_camera_matching
    accuracy, processing_time, section_json = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 862, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 815, in run_mtmc
    mm_data[cam][i]['detections'].append([matched_tid,x,y,w,h])
KeyError: 96

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '10',
  'lazy_threshold': 0.76,
  'model_size_camera1': 'yolov5x.pt',
  'model_size_camera2': 'yolov5m.pt',
  'resolution_camera1': '480',
  'resolution_camera2': '320',
})

[2024-03-28 22:37:08,963][0][INFO][generic_smbo.py:295] Iter 8, objectives: [inf, inf].
[2024-03-28 22:37:42,717][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_bo.py", line 103, in multi_camera_matching
    accuracy, processing_time, section_json = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 862, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 815, in run_mtmc
    mm_data[cam][i]['detections'].append([matched_tid,x,y,w,h])
KeyError: 95

config: Configuration(values={
  'fps_camera1': '5',
  'fps_camera2': '2',
  'lazy_threshold': 0.6,
  'model_size_camera1': 'yolov5x.pt',
  'model_size_camera2': 'yolov5x.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '480',
})

[2024-03-28 22:37:42,717][0][INFO][generic_smbo.py:295] Iter 9, objectives: [inf, inf].
[2024-03-28 22:37:42,719][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-03-28 22:38:22,190][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_bo.py", line 103, in multi_camera_matching
    accuracy, processing_time, section_json = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 862, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 815, in run_mtmc
    mm_data[cam][i]['detections'].append([matched_tid,x,y,w,h])
KeyError: 106

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '1',
  'lazy_threshold': 0.88,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'resolution_camera1': '480',
  'resolution_camera2': '640',
})

[2024-03-28 22:38:22,191][0][INFO][generic_smbo.py:295] Iter 10, objectives: [inf, inf].
[2024-03-28 22:38:22,192][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-03-28 22:38:46,520][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_bo.py", line 103, in multi_camera_matching
    accuracy, processing_time, section_json = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 862, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 815, in run_mtmc
    mm_data[cam][i]['detections'].append([matched_tid,x,y,w,h])
KeyError: 96

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '10',
  'lazy_threshold': 0.8,
  'model_size_camera1': 'yolov5x.pt',
  'model_size_camera2': 'yolov5l.pt',
  'resolution_camera1': '480',
  'resolution_camera2': '640',
})

[2024-03-28 22:38:46,521][0][INFO][generic_smbo.py:295] Iter 11, objectives: [inf, inf].
[2024-03-28 22:38:46,522][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-03-28 22:39:16,800][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_bo.py", line 103, in multi_camera_matching
    accuracy, processing_time, section_json = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 862, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 815, in run_mtmc
    mm_data[cam][i]['detections'].append([matched_tid,x,y,w,h])
KeyError: 190

config: Configuration(values={
  'fps_camera1': '5',
  'fps_camera2': '10',
  'lazy_threshold': 0.88,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
})

[2024-03-28 22:39:16,800][0][INFO][generic_smbo.py:295] Iter 12, objectives: [inf, inf].
[2024-03-28 22:39:16,802][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-03-28 22:39:33,095][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_bo.py", line 103, in multi_camera_matching
    accuracy, processing_time, section_json = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 862, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 815, in run_mtmc
    mm_data[cam][i]['detections'].append([matched_tid,x,y,w,h])
KeyError: 100

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '10',
  'lazy_threshold': 0.86,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
})

[2024-03-28 22:39:33,096][0][INFO][generic_smbo.py:295] Iter 13, objectives: [inf, inf].
[2024-03-28 22:39:33,097][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-03-28 22:40:09,241][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_bo.py", line 103, in multi_camera_matching
    accuracy, processing_time, section_json = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 862, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 815, in run_mtmc
    mm_data[cam][i]['detections'].append([matched_tid,x,y,w,h])
KeyError: 100

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '1',
  'lazy_threshold': 0.82,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '480',
})

[2024-03-28 22:40:09,241][0][INFO][generic_smbo.py:295] Iter 14, objectives: [inf, inf].
[2024-03-28 22:40:09,243][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-03-28 22:40:46,530][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_bo.py", line 103, in multi_camera_matching
    accuracy, processing_time, section_json = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 862, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 815, in run_mtmc
    mm_data[cam][i]['detections'].append([matched_tid,x,y,w,h])
KeyError: 94

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '2',
  'lazy_threshold': 0.8999999999999999,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5m.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '960',
})

[2024-03-28 22:40:46,530][0][INFO][generic_smbo.py:295] Iter 15, objectives: [inf, inf].
[2024-03-28 22:40:46,532][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-03-28 22:41:26,541][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_bo.py", line 103, in multi_camera_matching
    accuracy, processing_time, section_json = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 862, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 815, in run_mtmc
    mm_data[cam][i]['detections'].append([matched_tid,x,y,w,h])
KeyError: 190

config: Configuration(values={
  'fps_camera1': '5',
  'fps_camera2': '2',
  'lazy_threshold': 0.86,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5x.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
})

[2024-03-28 22:41:26,543][0][INFO][generic_smbo.py:295] Iter 16, objectives: [inf, inf].
[2024-03-28 22:41:26,544][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-03-28 22:41:57,163][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_bo.py", line 103, in multi_camera_matching
    accuracy, processing_time, section_json = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 862, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 815, in run_mtmc
    mm_data[cam][i]['detections'].append([matched_tid,x,y,w,h])
KeyError: 95

config: Configuration(values={
  'fps_camera1': '5',
  'fps_camera2': '2',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '1280',
})

[2024-03-28 22:41:57,164][0][INFO][generic_smbo.py:295] Iter 17, objectives: [inf, inf].
[2024-03-28 22:41:57,165][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-03-28 22:42:11,837][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_bo.py", line 103, in multi_camera_matching
    accuracy, processing_time, section_json = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 862, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 815, in run_mtmc
    mm_data[cam][i]['detections'].append([matched_tid,x,y,w,h])
KeyError: 18

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '10',
  'lazy_threshold': 0.88,
  'model_size_camera1': 'yolov5x.pt',
  'model_size_camera2': 'yolov5s.pt',
  'resolution_camera1': '960',
  'resolution_camera2': '480',
})

[2024-03-28 22:42:11,838][0][INFO][generic_smbo.py:295] Iter 18, objectives: [inf, inf].
[2024-03-28 22:42:11,839][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-03-28 22:42:42,310][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_bo.py", line 103, in multi_camera_matching
    accuracy, processing_time, section_json = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 862, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 815, in run_mtmc
    mm_data[cam][i]['detections'].append([matched_tid,x,y,w,h])
KeyError: 96

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '2',
  'lazy_threshold': 0.6,
  'model_size_camera1': 'yolov5x.pt',
  'model_size_camera2': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '960',
})

[2024-03-28 22:42:42,311][0][INFO][generic_smbo.py:295] Iter 19, objectives: [inf, inf].
[2024-03-28 22:42:42,312][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-03-28 22:43:33,284][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_bo.py", line 103, in multi_camera_matching
    accuracy, processing_time, section_json = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 862, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 815, in run_mtmc
    mm_data[cam][i]['detections'].append([matched_tid,x,y,w,h])
KeyError: 95

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '1',
  'lazy_threshold': 0.64,
  'model_size_camera1': 'yolov5x.pt',
  'model_size_camera2': 'yolov5m.pt',
  'resolution_camera1': '480',
  'resolution_camera2': '1280',
})

[2024-03-28 22:43:33,285][0][INFO][generic_smbo.py:295] Iter 20, objectives: [inf, inf].
[2024-03-28 22:43:33,286][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-03-28 22:43:57,962][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_bo.py", line 103, in multi_camera_matching
    accuracy, processing_time, section_json = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 862, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 815, in run_mtmc
    mm_data[cam][i]['detections'].append([matched_tid,x,y,w,h])
KeyError: 94

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '5',
  'lazy_threshold': 0.72,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '640',
})

[2024-03-28 22:43:57,966][0][INFO][generic_smbo.py:295] Iter 21, objectives: [inf, inf].
[2024-03-28 22:43:57,968][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-03-28 22:44:27,357][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_bo.py", line 103, in multi_camera_matching
    accuracy, processing_time, section_json = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 862, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 815, in run_mtmc
    mm_data[cam][i]['detections'].append([matched_tid,x,y,w,h])
KeyError: 100

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '2',
  'lazy_threshold': 0.86,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5x.pt',
  'resolution_camera1': '960',
  'resolution_camera2': '640',
})

[2024-03-28 22:44:27,358][0][INFO][generic_smbo.py:295] Iter 22, objectives: [inf, inf].
[2024-03-28 22:44:27,359][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-03-28 22:44:52,939][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_bo.py", line 103, in multi_camera_matching
    accuracy, processing_time, section_json = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 862, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 815, in run_mtmc
    mm_data[cam][i]['detections'].append([matched_tid,x,y,w,h])
KeyError: 96

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '5',
  'lazy_threshold': 0.86,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'resolution_camera1': '480',
  'resolution_camera2': '960',
})

[2024-03-28 22:44:52,940][0][INFO][generic_smbo.py:295] Iter 23, objectives: [inf, inf].
[2024-03-28 22:44:52,941][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-03-28 22:45:18,173][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_bo.py", line 103, in multi_camera_matching
    accuracy, processing_time, section_json = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 862, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 815, in run_mtmc
    mm_data[cam][i]['detections'].append([matched_tid,x,y,w,h])
KeyError: 96

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '5',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '320',
})

[2024-03-28 22:45:18,174][0][INFO][generic_smbo.py:295] Iter 24, objectives: [inf, inf].
[2024-03-28 22:45:18,175][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-03-28 22:45:44,381][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_bo.py", line 103, in multi_camera_matching
    accuracy, processing_time, section_json = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 862, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 815, in run_mtmc
    mm_data[cam][i]['detections'].append([matched_tid,x,y,w,h])
KeyError: 215

config: Configuration(values={
  'fps_camera1': '5',
  'fps_camera2': '10',
  'lazy_threshold': 0.6,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
})

[2024-03-28 22:45:44,382][0][INFO][generic_smbo.py:295] Iter 25, objectives: [inf, inf].
[2024-03-28 22:45:44,382][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-03-28 22:46:13,303][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_bo.py", line 103, in multi_camera_matching
    accuracy, processing_time, section_json = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 862, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 815, in run_mtmc
    mm_data[cam][i]['detections'].append([matched_tid,x,y,w,h])
KeyError: 100

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '2',
  'lazy_threshold': 0.6,
  'model_size_camera1': 'yolov5x.pt',
  'model_size_camera2': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '640',
})

[2024-03-28 22:46:13,304][0][INFO][generic_smbo.py:295] Iter 26, objectives: [inf, inf].
[2024-03-28 22:46:13,306][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-03-28 22:46:32,954][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_bo.py", line 103, in multi_camera_matching
    accuracy, processing_time, section_json = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 862, in profile
    mm_data, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/S03_mcmt.py", line 815, in run_mtmc
    mm_data[cam][i]['detections'].append([matched_tid,x,y,w,h])
KeyError: 105

config: Configuration(values={
  'fps_camera1': '5',
  'fps_camera2': '5',
  'lazy_threshold': 0.82,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '480',
})

[2024-03-28 22:46:32,955][0][INFO][generic_smbo.py:295] Iter 27, objectives: [inf, inf].
[2024-03-28 22:46:32,957][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
