[2024-01-23 22:49:15,327][0][INFO][color_logger.py:203] Logfile: /data1/xiayuyang/online_mcmt/logs/0_2024-01-23-22-49-15-326647.log
[2024-01-23 22:49:17,170][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 912, in profile
    gt_detect, gt_dict, total_detect_time, total_extract_time, total_sct_time, total_pp_time, total_match_time=run_mtmc(cams_dir=cams_dir_, weights=weights_, imgsz=imgsz_, cams_ratio=cams_ratio_, lazy_threshold=lazy_threshold_)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 525, in run_mtmc
    det_model = attempt_load(weights, map_location=device)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/models/experimental.py", line 122, in attempt_load
    model.append(torch.load(os.path.join(os.path.dirname(os.path.dirname(os.path.realpath(__file__))), w),
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/models/yolo.py", line 164, in fuse
    print('Fusing layers... ')
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '1',
  'fps_camera3': '1',
  'fps_camera4': '1',
  'fps_camera5': '1',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-23 22:49:17,171][0][INFO][generic_smbo.py:295] Iter 1, objectives: [inf, inf].
[2024-01-23 22:49:17,172][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '10',
  'fps_camera3': '10',
  'fps_camera4': '10',
  'fps_camera5': '1',
  'lazy_threshold': 0.64,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-23 22:49:17,173][0][INFO][generic_smbo.py:295] Iter 2, objectives: [inf, inf].
[2024-01-23 22:49:17,173][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '1',
  'fps_camera3': '4',
  'fps_camera4': '1',
  'fps_camera5': '10',
  'lazy_threshold': 0.72,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-23 22:49:17,174][0][INFO][generic_smbo.py:295] Iter 3, objectives: [inf, inf].
[2024-01-23 22:49:17,174][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '10',
  'fps_camera3': '4',
  'fps_camera4': '2',
  'fps_camera5': '10',
  'lazy_threshold': 0.78,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '320',
})

[2024-01-23 22:49:17,174][0][INFO][generic_smbo.py:295] Iter 4, objectives: [inf, inf].
[2024-01-23 22:49:17,175][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '10',
  'fps_camera3': '1',
  'fps_camera4': '1',
  'fps_camera5': '1',
  'lazy_threshold': 0.76,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-23 22:49:17,175][0][INFO][generic_smbo.py:295] Iter 5, objectives: [inf, inf].
[2024-01-23 22:49:17,176][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '10',
  'fps_camera3': '2',
  'fps_camera4': '10',
  'fps_camera5': '1',
  'lazy_threshold': 0.82,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '320',
})

[2024-01-23 22:49:17,176][0][INFO][generic_smbo.py:295] Iter 6, objectives: [inf, inf].
[2024-01-23 22:49:17,177][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '1',
  'fps_camera3': '2',
  'fps_camera4': '10',
  'fps_camera5': '1',
  'lazy_threshold': 0.6599999999999999,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '640',
})

[2024-01-23 22:49:17,177][0][INFO][generic_smbo.py:295] Iter 7, objectives: [inf, inf].
[2024-01-23 22:49:17,178][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '4',
  'fps_camera3': '10',
  'fps_camera4': '1',
  'fps_camera5': '1',
  'lazy_threshold': 0.86,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '640',
})

[2024-01-23 22:49:17,178][0][INFO][generic_smbo.py:295] Iter 8, objectives: [inf, inf].
[2024-01-23 22:49:17,179][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '2',
  'fps_camera3': '1',
  'fps_camera4': '4',
  'fps_camera5': '10',
  'lazy_threshold': 0.84,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '640',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '320',
})

[2024-01-23 22:49:17,179][0][INFO][generic_smbo.py:295] Iter 9, objectives: [inf, inf].
[2024-01-23 22:49:17,180][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,182][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '2',
  'fps_camera3': '1',
  'fps_camera4': '2',
  'fps_camera5': '2',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-23 22:49:17,182][0][INFO][generic_smbo.py:295] Iter 10, objectives: [inf, inf].
[2024-01-23 22:49:17,183][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,184][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '10',
  'fps_camera3': '2',
  'fps_camera4': '1',
  'fps_camera5': '4',
  'lazy_threshold': 0.6599999999999999,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '640',
  'resolution_camera3': '1280',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-23 22:49:17,184][0][INFO][generic_smbo.py:295] Iter 11, objectives: [inf, inf].
[2024-01-23 22:49:17,185][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,186][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '1',
  'fps_camera3': '4',
  'fps_camera4': '2',
  'fps_camera5': '4',
  'lazy_threshold': 0.78,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '640',
  'resolution_camera3': '320',
  'resolution_camera4': '640',
  'resolution_camera5': '1280',
})

[2024-01-23 22:49:17,186][0][INFO][generic_smbo.py:295] Iter 12, objectives: [inf, inf].
[2024-01-23 22:49:17,187][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,188][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '1',
  'fps_camera3': '4',
  'fps_camera4': '2',
  'fps_camera5': '2',
  'lazy_threshold': 0.6599999999999999,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '640',
  'resolution_camera3': '320',
  'resolution_camera4': '640',
  'resolution_camera5': '1280',
})

[2024-01-23 22:49:17,189][0][INFO][generic_smbo.py:295] Iter 13, objectives: [inf, inf].
[2024-01-23 22:49:17,189][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,190][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '2',
  'fps_camera3': '1',
  'fps_camera4': '4',
  'fps_camera5': '4',
  'lazy_threshold': 0.74,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '640',
  'resolution_camera5': '1280',
})

[2024-01-23 22:49:17,191][0][INFO][generic_smbo.py:295] Iter 14, objectives: [inf, inf].
[2024-01-23 22:49:17,191][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,192][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '1',
  'fps_camera3': '1',
  'fps_camera4': '2',
  'fps_camera5': '2',
  'lazy_threshold': 0.6599999999999999,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-23 22:49:17,193][0][INFO][generic_smbo.py:295] Iter 15, objectives: [inf, inf].
[2024-01-23 22:49:17,193][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,194][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '2',
  'fps_camera3': '2',
  'fps_camera4': '2',
  'fps_camera5': '4',
  'lazy_threshold': 0.6799999999999999,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '640',
  'resolution_camera3': '320',
  'resolution_camera4': '640',
  'resolution_camera5': '640',
})

[2024-01-23 22:49:17,195][0][INFO][generic_smbo.py:295] Iter 16, objectives: [inf, inf].
[2024-01-23 22:49:17,195][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,197][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '1',
  'fps_camera3': '2',
  'fps_camera4': '1',
  'fps_camera5': '4',
  'lazy_threshold': 0.6799999999999999,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-23 22:49:17,197][0][INFO][generic_smbo.py:295] Iter 17, objectives: [inf, inf].
[2024-01-23 22:49:17,197][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,199][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '4',
  'fps_camera3': '2',
  'fps_camera4': '10',
  'fps_camera5': '4',
  'lazy_threshold': 0.86,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '640',
  'resolution_camera5': '1280',
})

[2024-01-23 22:49:17,199][0][INFO][generic_smbo.py:295] Iter 18, objectives: [inf, inf].
[2024-01-23 22:49:17,199][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,201][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '4',
  'fps_camera3': '4',
  'fps_camera4': '2',
  'fps_camera5': '10',
  'lazy_threshold': 0.6,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-23 22:49:17,201][0][INFO][generic_smbo.py:295] Iter 19, objectives: [inf, inf].
[2024-01-23 22:49:17,201][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,203][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '1',
  'fps_camera3': '2',
  'fps_camera4': '2',
  'fps_camera5': '2',
  'lazy_threshold': 0.78,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '640',
  'resolution_camera3': '640',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-23 22:49:17,203][0][INFO][generic_smbo.py:295] Iter 20, objectives: [inf, inf].
[2024-01-23 22:49:17,204][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,205][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '2',
  'fps_camera3': '10',
  'fps_camera4': '4',
  'fps_camera5': '1',
  'lazy_threshold': 0.8,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '640',
  'resolution_camera3': '320',
  'resolution_camera4': '640',
  'resolution_camera5': '1280',
})

[2024-01-23 22:49:17,205][0][INFO][generic_smbo.py:295] Iter 21, objectives: [inf, inf].
[2024-01-23 22:49:17,206][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,207][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '4',
  'fps_camera3': '1',
  'fps_camera4': '2',
  'fps_camera5': '10',
  'lazy_threshold': 0.62,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '640',
  'resolution_camera3': '1280',
  'resolution_camera4': '640',
  'resolution_camera5': '640',
})

[2024-01-23 22:49:17,208][0][INFO][generic_smbo.py:295] Iter 22, objectives: [inf, inf].
[2024-01-23 22:49:17,208][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,210][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '10',
  'fps_camera3': '4',
  'fps_camera4': '1',
  'fps_camera5': '2',
  'lazy_threshold': 0.6799999999999999,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-23 22:49:17,210][0][INFO][generic_smbo.py:295] Iter 23, objectives: [inf, inf].
[2024-01-23 22:49:17,210][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,212][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '2',
  'fps_camera3': '4',
  'fps_camera4': '1',
  'fps_camera5': '4',
  'lazy_threshold': 0.6599999999999999,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '640',
})

[2024-01-23 22:49:17,212][0][INFO][generic_smbo.py:295] Iter 24, objectives: [inf, inf].
[2024-01-23 22:49:17,213][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,214][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '2',
  'fps_camera3': '10',
  'fps_camera4': '10',
  'fps_camera5': '1',
  'lazy_threshold': 0.8,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '640',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '640',
})

[2024-01-23 22:49:17,214][0][INFO][generic_smbo.py:295] Iter 25, objectives: [inf, inf].
[2024-01-23 22:49:17,215][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,216][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '2',
  'fps_camera3': '1',
  'fps_camera4': '10',
  'fps_camera5': '4',
  'lazy_threshold': 0.78,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '640',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-23 22:49:17,217][0][INFO][generic_smbo.py:295] Iter 26, objectives: [inf, inf].
[2024-01-23 22:49:17,217][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-01-23 22:49:17,218][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '1',
  'fps_camera3': '4',
  'fps_camera4': '4',
  'fps_camera5': '2',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '640',
})

[2024-01-23 22:49:17,218][0][INFO][generic_smbo.py:295] Iter 27, objectives: [inf, inf].
[2024-01-23 22:49:17,219][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,220][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '10',
  'fps_camera3': '4',
  'fps_camera4': '10',
  'fps_camera5': '1',
  'lazy_threshold': 0.6599999999999999,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '1280',
  'resolution_camera3': '640',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-23 22:49:17,220][0][INFO][generic_smbo.py:295] Iter 28, objectives: [inf, inf].
[2024-01-23 22:49:17,221][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,222][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '4',
  'fps_camera3': '4',
  'fps_camera4': '1',
  'fps_camera5': '2',
  'lazy_threshold': 0.88,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '320',
  'resolution_camera5': '640',
})

[2024-01-23 22:49:17,222][0][INFO][generic_smbo.py:295] Iter 29, objectives: [inf, inf].
[2024-01-23 22:49:17,223][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,224][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '10',
  'fps_camera3': '1',
  'fps_camera4': '4',
  'fps_camera5': '2',
  'lazy_threshold': 0.64,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '640',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '640',
})

[2024-01-23 22:49:17,225][0][INFO][generic_smbo.py:295] Iter 30, objectives: [inf, inf].
[2024-01-23 22:49:17,225][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,227][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '2',
  'fps_camera3': '2',
  'fps_camera4': '4',
  'fps_camera5': '1',
  'lazy_threshold': 0.6,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '640',
  'resolution_camera5': '1280',
})

[2024-01-23 22:49:17,227][0][INFO][generic_smbo.py:295] Iter 31, objectives: [inf, inf].
[2024-01-23 22:49:17,227][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,229][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '2',
  'fps_camera3': '2',
  'fps_camera4': '4',
  'fps_camera5': '2',
  'lazy_threshold': 0.8,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '640',
  'resolution_camera3': '640',
  'resolution_camera4': '640',
  'resolution_camera5': '320',
})

[2024-01-23 22:49:17,229][0][INFO][generic_smbo.py:295] Iter 32, objectives: [inf, inf].
[2024-01-23 22:49:17,230][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,231][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '1',
  'fps_camera3': '4',
  'fps_camera4': '4',
  'fps_camera5': '2',
  'lazy_threshold': 0.64,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-23 22:49:17,231][0][INFO][generic_smbo.py:295] Iter 33, objectives: [inf, inf].
[2024-01-23 22:49:17,232][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,233][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '4',
  'fps_camera3': '1',
  'fps_camera4': '10',
  'fps_camera5': '2',
  'lazy_threshold': 0.72,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '1280',
})

[2024-01-23 22:49:17,234][0][INFO][generic_smbo.py:295] Iter 34, objectives: [inf, inf].
[2024-01-23 22:49:17,234][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,236][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '4',
  'fps_camera3': '10',
  'fps_camera4': '4',
  'fps_camera5': '2',
  'lazy_threshold': 0.6799999999999999,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '640',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-23 22:49:17,236][0][INFO][generic_smbo.py:295] Iter 35, objectives: [inf, inf].
[2024-01-23 22:49:17,236][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,238][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '4',
  'fps_camera3': '2',
  'fps_camera4': '4',
  'fps_camera5': '1',
  'lazy_threshold': 0.82,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '640',
  'resolution_camera4': '1280',
  'resolution_camera5': '640',
})

[2024-01-23 22:49:17,238][0][INFO][generic_smbo.py:295] Iter 36, objectives: [inf, inf].
[2024-01-23 22:49:17,238][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,240][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '1',
  'fps_camera3': '10',
  'fps_camera4': '4',
  'fps_camera5': '4',
  'lazy_threshold': 0.64,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '640',
  'resolution_camera5': '1280',
})

[2024-01-23 22:49:17,240][0][INFO][generic_smbo.py:295] Iter 37, objectives: [inf, inf].
[2024-01-23 22:49:17,240][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,244][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '1',
  'fps_camera3': '4',
  'fps_camera4': '2',
  'fps_camera5': '1',
  'lazy_threshold': 0.74,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-23 22:49:17,245][0][INFO][generic_smbo.py:295] Iter 38, objectives: [inf, inf].
[2024-01-23 22:49:17,246][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,250][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '4',
  'fps_camera3': '2',
  'fps_camera4': '2',
  'fps_camera5': '4',
  'lazy_threshold': 0.64,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-23 22:49:17,250][0][INFO][generic_smbo.py:295] Iter 39, objectives: [inf, inf].
[2024-01-23 22:49:17,252][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,255][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '4',
  'fps_camera3': '1',
  'fps_camera4': '4',
  'fps_camera5': '4',
  'lazy_threshold': 0.8,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5l.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '640',
  'resolution_camera5': '320',
})

[2024-01-23 22:49:17,256][0][INFO][generic_smbo.py:295] Iter 40, objectives: [inf, inf].
[2024-01-23 22:49:17,257][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,260][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '4',
  'fps_camera3': '4',
  'fps_camera4': '2',
  'fps_camera5': '1',
  'lazy_threshold': 0.64,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '640',
})

[2024-01-23 22:49:17,260][0][INFO][generic_smbo.py:295] Iter 41, objectives: [inf, inf].
[2024-01-23 22:49:17,260][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-01-23 22:49:17,262][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '2',
  'fps_camera3': '2',
  'fps_camera4': '4',
  'fps_camera5': '2',
  'lazy_threshold': 0.86,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '1280',
})

[2024-01-23 22:49:17,262][0][INFO][generic_smbo.py:295] Iter 42, objectives: [inf, inf].
[2024-01-23 22:49:17,263][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,265][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '1',
  'fps_camera3': '1',
  'fps_camera4': '10',
  'fps_camera5': '4',
  'lazy_threshold': 0.6,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '640',
  'resolution_camera3': '1280',
  'resolution_camera4': '320',
  'resolution_camera5': '320',
})

[2024-01-23 22:49:17,265][0][INFO][generic_smbo.py:295] Iter 43, objectives: [inf, inf].
[2024-01-23 22:49:17,266][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,267][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '10',
  'fps_camera3': '10',
  'fps_camera4': '10',
  'fps_camera5': '2',
  'lazy_threshold': 0.88,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5l.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '320',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '640',
})

[2024-01-23 22:49:17,268][0][INFO][generic_smbo.py:295] Iter 44, objectives: [inf, inf].
[2024-01-23 22:49:17,268][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,270][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '2',
  'fps_camera3': '10',
  'fps_camera4': '4',
  'fps_camera5': '2',
  'lazy_threshold': 0.8999999999999999,
  'model_size_camera1': 'yolov5m.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '640',
})

[2024-01-23 22:49:17,270][0][INFO][generic_smbo.py:295] Iter 45, objectives: [inf, inf].
[2024-01-23 22:49:17,270][0][INFO][generic_advisor.py:365] Sample random config. rand_prob=0.100000.
[2024-01-23 22:49:17,272][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '1',
  'fps_camera2': '10',
  'fps_camera3': '10',
  'fps_camera4': '4',
  'fps_camera5': '10',
  'lazy_threshold': 0.7,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5s.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '1280',
  'resolution_camera2': '640',
  'resolution_camera3': '1280',
  'resolution_camera4': '640',
  'resolution_camera5': '320',
})

[2024-01-23 22:49:17,272][0][INFO][generic_smbo.py:295] Iter 46, objectives: [inf, inf].
[2024-01-23 22:49:17,274][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,275][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '4',
  'fps_camera2': '2',
  'fps_camera3': '2',
  'fps_camera4': '1',
  'fps_camera5': '1',
  'lazy_threshold': 0.82,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5m.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '640',
  'resolution_camera3': '320',
  'resolution_camera4': '640',
  'resolution_camera5': '640',
})

[2024-01-23 22:49:17,276][0][INFO][generic_smbo.py:295] Iter 47, objectives: [inf, inf].
[2024-01-23 22:49:17,276][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,278][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '2',
  'fps_camera3': '10',
  'fps_camera4': '4',
  'fps_camera5': '2',
  'lazy_threshold': 0.78,
  'model_size_camera1': 'yolov5l.pt',
  'model_size_camera2': 'yolov5l.pt',
  'model_size_camera3': 'yolov5l.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '1280',
  'resolution_camera3': '1280',
  'resolution_camera4': '1280',
  'resolution_camera5': '640',
})

[2024-01-23 22:49:17,278][0][INFO][generic_smbo.py:295] Iter 48, objectives: [inf, inf].
[2024-01-23 22:49:17,279][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,281][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '2',
  'fps_camera2': '4',
  'fps_camera3': '4',
  'fps_camera4': '4',
  'fps_camera5': '10',
  'lazy_threshold': 0.78,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5s.pt',
  'model_size_camera5': 'yolov5m.pt',
  'resolution_camera1': '320',
  'resolution_camera2': '320',
  'resolution_camera3': '320',
  'resolution_camera4': '1280',
  'resolution_camera5': '640',
})

[2024-01-23 22:49:17,281][0][INFO][generic_smbo.py:295] Iter 49, objectives: [inf, inf].
[2024-01-23 22:49:17,282][0][WARNING][generic_advisor.py:375] No enough successful initial trials! Sample random configuration.
[2024-01-23 22:49:17,283][0][ERROR][generic_smbo.py:275] Exception in objective function:
Traceback (most recent call last):
  File "/data1/xiayuyang/anaconda3/envs/carla/lib/python3.8/site-packages/openbox/utils/limit.py", line 62, in run_without_time_limit
    ret = obj_func(*obj_args, **obj_kwargs)
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/bo.py", line 80, in multi_camera_matching
    accuracy, processing_time = profile(
  File "/data1/xiayuyang/online_mcmt/detector/yolov5/my_mtmc.py", line 909, in profile
    print("传过来的参数:", cams_dir_, weights_, imgsz_, cams_ratio_, lazy_threshold_, gpu_id)
OSError: [Errno 5] Input/output error

config: Configuration(values={
  'fps_camera1': '10',
  'fps_camera2': '4',
  'fps_camera3': '1',
  'fps_camera4': '4',
  'fps_camera5': '4',
  'lazy_threshold': 0.76,
  'model_size_camera1': 'yolov5s.pt',
  'model_size_camera2': 'yolov5s.pt',
  'model_size_camera3': 'yolov5m.pt',
  'model_size_camera4': 'yolov5m.pt',
  'model_size_camera5': 'yolov5s.pt',
  'resolution_camera1': '640',
  'resolution_camera2': '1280',
  'resolution_camera3': '320',
  'resolution_camera4': '320',
  'resolution_camera5': '640',
})

[2024-01-23 22:49:17,284][0][INFO][generic_smbo.py:295] Iter 50, objectives: [inf, inf].
